### ISSUE TITLE
IDE shows cyclic connection where there isn't any.

### ISSUE THREAD

**Issue by BinarySoftware** [enso-org/ide#1000]
### General Summary
Given the code
```
foo = Foo x y
```
node will show connection to itself, as if it was

```
Foo = Foo x y
```

The same occurs with:
```
file = File.read "path"
```

**Comment by wdanilo** [comment]
Its not a bug. This is by desing. It's part of UCF (Uniform Call Syntax). We will be removing UCF from language soon, but now, this is not a bug.
