### ISSUE TITLE
Histogram Data Frames support

### ISSUE THREAD

**Issue by farmaazon** [enso-org/ide#1022]
Dataframe feeding the visualization should have column `value`. In case of lacking `value` column the histogram should be appl to first numerical column.ie to first numerical column.d to first numerical column.

The visualizations should use preprocessor expression to make sure only appropriate columns will be sent from Engine. [Here are examples of using Table type, representing DataFrames in Enso](https://github.com/enso-org/enso/blob/main/distribution/std-lib/Table/src/Main.enso).

**Comment by farmaazon** [comment]
Additionally, the histogram should not use any bins by default: just show count of each value in array/table.

**Comment by MichaelMauderer** [comment]
> Additionally, the histogram should not use any bins by default: just show count of each value in array/table.

I'm not sure if that makes any sense. Think of a random distribution between -1 and 1 with a couple million values. We do not want to compute or show a single bar for each value. And we do not want to bin them to just integer bins. Neither provides a useful starting point for showing or exploring the data. Any default bins need in some way be based on the data.

**Comment by farmaazon** [comment]
> > Additionally, the histogram should not use any bins by default: just show count of each value in array/table.
> 
> I'm not sure if that makes any sense. Think of a random distribution between -1 and 1 with a couple million values. We do not want to compute or show a single bar for each value. And we do not want to bin them to just integer bins. Neither provides a useful starting point for showing or exploring the data. Any default bins need in some way be based on the data.

cc @wdanilo

**Comment by farmaazon** [comment]
Conclusion: just change the default number of bins to 50.
