### ISSUE TITLE
Display error on nodes in GraphEditor

### ISSUE THREAD

**Issue by farmaazon** [enso-org/ide#1025]
### Summary
GraphEditor should have a new FRP input for receiving information about errors on nodes, or about lack of such. The errors should be shown on the screen as described in the epic https://github.com/enso-org/ide/issues/1024 (without visualization).

### Acceptance Criteria & Test Cases
A node with error in some example scene.

**Comment by sylwiabr** [comment]
@MichaelMauderer @wdanilo which example scene is it?

**Comment by wdanilo** [comment]
It should be part of `entry=interface` on master. If it's not, then @MichaelMauderer you should add it. I was watching that on Michael's screen, so if its not part of `interface` its a mistake.

**Comment by MichaelMauderer** [comment]
@sylwiabr this is part of the `entry=interface` debug scene. There is a node in that scene that shows an error.
