### ISSUE TITLE
Build electron package with bundled Project Manager

### ISSUE THREAD

**Issue by farmaazon** [enso-org/ide#1029]
### Summary
The new Engine's Project Manager (which does not require any setup anymore) should be bundled in IDE Electron Package, and the PM process should be automatically launched on IDE startup.

### Value
User can just double click on Enso IDE executable to start working.

### Specification
* The PM executable shall be downloaded during build from GH actions or release of Engine repository. There should be a constant with exact version/commit required by IDE.
* The pure PM on fresh system won't download and install any component until directly asked for. Therefore the IDE should be updated to handle "MissingComponentError" and resend request for project creation/opening with appropriate "missingComponentAction" argument. (see https://dev.enso.org/docs/enso/language-server/protocol-project-manager.html#projectcreate)

### Acceptance Criteria & Test Cases
Click and run.

**Comment by farmaazon** [comment]
* Call @wdanilo before working on it, because he knows the "electron packaging" process well.
* In general: we create a directories with some components (server, web content) - the PM should be downloaded and put into some directory, and the main script should run Project Manager.

**Comment by sylwiabr** [comment]
this should also support installing and running with local engine (`--local path_to_engine_package`) and installing last nightly build (`--nightly`)

**Comment by farmaazon** [comment]
Thus it may exceed the estimate. @MichaelMauderer let's make first PR for the bundling, then we think how to pass options to the PM (if they will be available).

**Comment by sylwiabr** [comment]
ok so question: there are options to run PM with local engine - is it possible to pass them through on IDE start?

**Comment by iamrecursion** [comment]
This should now use the official [releases](https://github.com/enso-org/enso/releases) rather than the staging repo.

**Comment by sylwiabr** [comment]
Question: from what I understand after switching to enso releases there is everything ready (inside IDE package will be both PM and Language server)? @farmaazon @iamrecursion

**Comment by sylwiabr** [comment]
There is an existing mechanism for running local LS with PM so from what I understand there is nothing blocking from Engine side?

**Comment by MichaelMauderer** [comment]
I believe right now the language server is loaded by the bundled project manager on demand. There is now this issue enso-org/ide#1106 solve this

**Comment by iamrecursion** [comment]
There's nothing left to do on our side. The LS will be launched by the PM on demand. Last we talked about this all that remained was for the IDE to bundle the PM, but also the Engine and Graal (for which I believe @radeusgd added the functionality to install from local).

**Comment by sylwiabr** [comment]
Added issue for passing args to PM https://app.zenhub.com/workspaces/enso-ide-5e99c2847b8a3027b334f1b9/issues/enso-org/ide/1213

<blockquote><img src="No image" width="48" align="right"><div><img src="/dist/favicon/favicon-16x16.png" height="14"> ZenHub</div><div><strong><a href="https://zenhub.com">ZenHub</a></strong></div><div>Project Management and Software Development with GitHub | ZenHub</div></blockquote>
