### ISSUE TITLE
Always assign new expression to a value

### ISSUE THREAD

**Issue by 4e6** [enso-org/ide#1067]
### General Summary

In the main flow, when we add node after node, we usually attach the visualization to the last expression. It is not cached, and the engine has to recompute it. 

```
main =
    list = 1.up_to 10 . to_vector
    operator1 = list.filter (>5)
    list.map (+1)
```
The engine cannot cache the intermediate expressions because then it can't guarantee that the program won't run out of memory.

An easy fix would be, when creating a new node in IDE, always assign it to a value.
```
main =
    list = 1.up_to 10 . to_vector
    operator1 = list.filter (>5)
    operator2 = list.map (+1)
    operator2
```

### Motivation

Improve visualization performance

**Comment by farmaazon** [comment]
I see a couple of problems here:
1. Yes, we can assign a new value to the node. However, the user will be able to put line without assignment in Code Editor. I understand, that then the visualization won't be cached?
2. For methods returning Nothing assigning to variable has no sense. But we don't know if node return Nothing until we actually place it.
