### ISSUE TITLE
Implement an IDE closing in cloud

### ISSUE THREAD

**Issue by lolczak** [enso-org/ide#1095]
### Summary
Please implement an IDE closing behavior and clean up HTML.

### Value
A user will be able to switch between projects in the Cloud UI.

### Specification
- [ ] Add an x button which should be visible only in cloud environment.
- [ ] the function should invoke a callback on exit registered at `window.enso.close`
- [ ] ~~suppress logging. Currently, the rate of logs is humongous, and a browser decides not to show any for the website. It hinders the debugging of the Cloud UI.~~

### Acceptance Criteria & Test Cases
The feature will be released as a release candidate and published to CDN.

**Comment by farmaazon** [comment]
The x should be in rust and should look like a close button in macOs.

**Comment by farmaazon** [comment]
* Add argument to window.enso.start with platform (cloud or desktop). The close button should displayed in cloud only

**Comment by wdanilo** [comment]
white theme:
![image](https://user-images.githubusercontent.com/1623053/114523175-5b653280-9c44-11eb-9c22-ea12ef10d0d0.png)

hover:
![image](https://user-images.githubusercontent.com/1623053/114523248-6ae47b80-9c44-11eb-8677-c8e444648cf7.png)

dark theme:
![image](https://user-images.githubusercontent.com/1623053/114523284-720b8980-9c44-11eb-8a98-00596bf12f58.png)

hover:
![image](https://user-images.githubusercontent.com/1623053/114523311-78016a80-9c44-11eb-98ae-6a8cbb4b0038.png)

**Comment by wdanilo** [comment]
Lets do read and green functions https://www.w3schools.com/howto/howto_js_fullscreen.asp

<blockquote><div><strong><a href="https://www.w3schools.com/howto/howto_js_fullscreen.asp">How To Change The Browser To Fullscreen with JavaScript</a></strong></div><div>Well organized and easy to understand Web building tutorials with lots of examples of how to use HTML, CSS, JavaScript, SQL, PHP, Python, Bootstrap, Java and XML.</div></blockquote>

**Comment by farmaazon** [comment]
> Lets do read and green functions https://www.w3schools.com/howto/howto_js_fullscreen.asp

I don't understand. Do you mean "red and green buttons"?

<blockquote><div><strong><a href="https://www.w3schools.com/howto/howto_js_fullscreen.asp">How To Change The Browser To Fullscreen with JavaScript</a></strong></div><div>Well organized and easy to understand Web building tutorials with lots of examples of how to use HTML, CSS, JavaScript, SQL, PHP, Python, Bootstrap, Java and XML.</div></blockquote>

**Comment by lolczak** [comment]
@stasyaner FYI
