### ISSUE TITLE
Check if those CSS classes are actually needed

### ISSUE THREAD

**Issue by lolczak** [enso-org/ide#1122]
### Summary
Check if the below CSS is correct.
Path: `src/js/lib/content/src/style.css`
```
.scrollable::-webkit-scrollbar:vertical {
  width: 11px;
}

.scrollable::-webkit-scrollbar:horizontal {
  height: 11px;
}
```

**Comment by farmaazon** [comment]
@lolczak Why we check that? What does the new css give us?

**Comment by lolczak** [comment]
@farmaazon 
Wojtek asked me to create this issue. @wdanilo can you shed light on it?

**Comment by farmaazon** [comment]
BR: 
* the classes are required by some visualizations. IT should be moved to the proper css inserted by visualization.
* the value 11 should be explained.
