### ISSUE TITLE
Sign Windows and MacOS binaries. 

### ISSUE THREAD

**Issue by MichaelMauderer** [enso-org/ide#1135]
### Summary
TBD by @MichaelMauderer

**Comment by farmaazon** [comment]
BR:
* Probably we could use old certificates (for Luna). Check it out with @sylwiabr @kustosz 
* First steps belong to @sylwiabr : to recover old accounts, and then see what next steps are required, to ultimately sign all packages with proper certificates on CI.

**Comment by sylwiabr** [comment]
I believe we have (or had) Win certificate from here https://www.digicert.com/tls-ssl/ - needs further investigation

<blockquote><div><strong><a href="https://www.digicert.com/tls-ssl/">TLS/SSL Certificates</a></strong></div><div>TLS/SSL certificates secure internet connections by encrypting data sent between your browser, the website you’re visiting, and the website server. </div></blockquote>

**Comment by sylwiabr** [comment]
The old certificate was just for a year so we need new one for Windows. To purchase a win certificate I need to choose server. Any ideas here @MichaelMauderer @farmaazon @wdanilo 
<img width="334" alt="Screenshot 2021-01-28 at 12 25 31" src="https://user-images.githubusercontent.com/12892578/106132340-1f055880-6164-11eb-8f32-fa9c3f25a02a.png">

**Comment by sylwiabr** [comment]
Learn more is giving me this: https://knowledge.digicert.com/alerts/Kernel-Mode.html

<blockquote><img src="/content/dam/digicertknowledgebase/favicon.png" width="48" align="right"><div><strong><a href="https://knowledge.digicert.com/alerts/Kernel-Mode.html">Microsoft sunsetting support for cross-signed root certificates with kernel-mode signing capabilities</a></strong></div></blockquote>

**Comment by sylwiabr** [comment]
Also there is a requirement of Certificate Signing Request (CSR):![Screenshot 2021-01-28 at 13.02.02.png](https://images.zenhubusercontent.com/5953b61961b4ca3b0a72960b/b0d1defc-8082-4d6c-8d6a-ff5119371cc9)

https://www.digicert.com/kb/csr-creation.htm

<blockquote><img src="/kb/images/new-digicert-favicon.ico" width="48" align="right"><div><strong><a href="https://www.digicert.com/kb/csr-creation.htm">CSR Creation | Create Certificate Signing Request | DigiCert</a></strong></div><div>Before ordering an SSL certificate, you need to generate a CSR. Find the creation instructions for most web server platforms and software here.</div></blockquote>

**Comment by sylwiabr** [comment]
I have a certificate for MacOS.

**Comment by sylwiabr** [comment]
https://docs.microsoft.com/en-us/windows/msix/package/create-certificate-package-signing

<blockquote><img src="https://docs.microsoft.com/en-us/media/logos/logo-ms-social.png" width="48" align="right"><div><strong><a href="https://docs.microsoft.com/en-us/windows/msix/package/create-certificate-package-signing">Create a certificate for package signing - MSIX</a></strong></div><div>Create and export a certificate for app package signing with PowerShell tools.</div></blockquote>
