### ISSUE TITLE
IDE crashes on some Linux systems

### ISSUE THREAD

**Issue by wdanilo** [enso-org/ide#1197]
The IDE crashes, we can see the following logs in the terminal:
![image](https://user-images.githubusercontent.com/1623053/107851243-c8a54480-6e08-11eb-9e13-1bf48396fa77.png)

It happens already on 2 Linux Systems (possibly the same hardware).

### What did you do?
- Just starting the IDE. Unfortunately, we do not have a reproducible system with this issue now.

### Enso Version
2.0.0-alpha.1

**Comment by wdanilo** [comment]
The error is very strange, suggesting that the WebGL Context initialized correctly, but it failed on some later operations (otherwise we would crash earlier, not when trying to use WebGL API!).

**Comment by wdanilo** [comment]
@zby , would you be so nice and provide us with the information about your hardware in both cases? Especially, CPU, GPU, system (with version), amount of RAM, and if that would not be a problem for you also with `./Enso --info` pasted on https://pastebin.com ?

<blockquote><img src="https://pastebin.com/i/facebook.png" width="48" align="right"><div>Pastebin</div><div><strong><a href="https://pastebin.com/">Pastebin.com - enso-org/enso#2009 paste tool since 2002!</a></strong></div><div>Pastebin.com is the number one paste tool since 2002. Pastebin is a website where you can store text online for a set period of time.</div></blockquote>

**Comment by zby** [comment]
OK - so I guess this is a CubesOS problem. I have tested it on three different virtual machines: debian 10, ubuntu bionic and fedora 30. Cubes have their special X patches and I guess that is interfering with some of that WebGL stuff.

**Comment by wdanilo** [comment]
@zby I was trying to search the web for similar problems on Qubes OS, but I was not able to find anything related. In case this is Qubes OS specific problem, and we are not going to support it in the close future (it's not a very popular platform + we don't have a reproducible environment + our team is small), I'd close it for now. However, if there would be other people from the community who are working on this system, please report similar issues here, and let's re-open the thread then.

**Comment by wdanilo** [comment]
@zby also, are you able to run other WebGL 2.0 applications on the newest Chromium, like these: http://webglsamples.org/WebGL2Samples ?

**Comment by zby** [comment]
The WebGL2Samples don't crash - but there are a few (3 maybe) that result in blank screen

**Comment by wdanilo** [comment]
@zby would you also be so nice to run https://www.khronos.org/registry/webgl/conformance-suites/2.0.0/webgl-conformance-tests.html (press "run all") and share with us the results you got there?

<blockquote><div><strong><a href="https://www.khronos.org/registry/webgl/conformance-suites/2.0.0/webgl-conformance-tests.html">WebGL Conformance Tests</a></strong></div></blockquote>
