### ISSUE TITLE
Slider component

### ISSUE THREAD

**Issue by farmaazon** [enso-org/ide#1199]
### Summary
* highly configurable
* ability to show caption with slider value.
* configurable minimum and maximum value.
* an option for disable jumping: clicking should not move the slider - only click and move.
* an option for scrolling under minimum or over maximum value.
* an option for adjusting min/max value when under/overscrolling.
* add option for making slider as a range slider (drag either end of slider to resize it (extending range) or in the middle to move it). With option to block resizing.
* Configured by FRP endpoints.

Visuals:
background: a rect with fully rounded corners.
a slider: similar.

### Value
* To use on nodes
* Sliders in visualizations.

### Acceptance Criteria & Test Cases
A debug scene with various slider configurations.

**Comment by MichaelMauderer** [comment]
Amendment:
* if the value is under or over-scrolled, this should be indicated by an arrow/triangle at the appropriate end of the slider area.
* the slider value should be shown at a static position, left right or centred on the slider area.
* the slider should be able to show a caption on the slider area. The caption should be non-interactive.
* the track should change size in accordance with the value. No other value signifier should be there, i.e., no handle, dot or arrow. at the location of the selected value. Only the coloured track.
* text labels should be centred on the decimal point.

**Comment by MichaelMauderer** [comment]
Amendment:
* in range selection mode the caption should be centered and range values should be displayed at each side of the slider.
* in range selection mode with overflow the overflow symbol (and area around) should be used to change the range value of the corresponding side.
