### ISSUE TITLE
After waking up Mac from sleep, IDE wont evaluate code anymore

### ISSUE THREAD

**Issue by BinarySoftware** [enso-org/ide#1208]
### What did you do?
- put my mac to sleep (close the lid)
- reopen it after some time, ex. 5 mins
- try working in ide

### What did you expect to see?
new nodes evaluated

### What did you see instead?
nothing new

**Comment by farmaazon** [comment]
To check if the issue occurs when PM is launched in terminal (with --no-backend option).

**Comment by farmaazon** [comment]
Partially fixed by displaying a "connection lost" error. Will be fully fixed with the reconnecting websockets issue.
