### ISSUE TITLE
Geo_Map visualizations stopped working

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/ide#1233]
### What did you do?

Constructed `Geo.point` and opened vis
### What did you expect to see?

Geo_Map viualization with a point
### What did you see instead?

blank vis on Geo_Map

https://user-images.githubusercontent.com/12892578/108985544-75958200-7691-11eb-9bc9-94b29e346675.mov

**Comment by MichaelMauderer** [comment]
I believe this is the same underlying issue as https://github.com/enso-org/ide/issues/1231
I can get the data to display correctly if I open the visualization via the space bar.

**Comment by sylwiabr** [comment]
Maybe it is about operating system then?

**Comment by sylwiabr** [comment]
After merging https://app.zenhub.com/workspaces/enso-ide-5e99c2847b8a3027b334f1b9/issues/enso-org/ide/1231 I still have a problem with Geo_Map not appearing 

<blockquote><img src="No image" width="48" align="right"><div><img src="/dist/favicon/favicon-16x16.png" height="14"> ZenHub</div><div><strong><a href="https://zenhub.com">ZenHub</a></strong></div><div>Project Management and Software Development with GitHub | ZenHub</div></blockquote>
