### ISSUE TITLE
after collapsing nodes I am getting null on collapsed function (inside there is active vis with result)

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/ide#1234]
### What did you do?

Add two connected nodes and collapse them
### What did you expect to see?

visualization on the collapsed node
### What did you see instead?

`null`

https://user-images.githubusercontent.com/12892578/108985464-5dbdfe00-7691-11eb-9c78-b0d70627ab00.mov

**Comment by sylwiabr** [comment]
I have one thing I would like to have: the newly added node is in completely random place - can we do it somehow consistently with the rest of the nodes?

**Comment by mwu-tow** [comment]
We can, though I'm not sure if this shouldn't be tracked as a separate issue. Has this behavior regressed with enso-org/ide#1260 ?

**Comment by farmaazon** [comment]
No, the output node was always at 0,0 (random place)

**Comment by sylwiabr** [comment]
This is the same issue - this is a UX regression for me

**Comment by wdanilo** [comment]
Yup, this is UX regression. Earlier, when collapsing nodes we had nice looking graph, now we have a mess inside, this is definitely a regression from the UX perspective.

**Comment by farmaazon** [comment]
@wdanilo @sylwiabr But this isn't! Every time I did the basic scenario from https://docs.google.com/spreadsheets/d/1RatJDM_f9_3bvYhl3Bpq2d8SyKgtVdrV1RkGxPU17c8/edit#gid=0 the last node was put in the middle of scene

<blockquote><img src="https://lh4.googleusercontent.com/EHFuOyujZSYy3kc2fQtTdwjF2T749q80UlXXKeb619R4h-z611GP79dQqo-7sIROBvU1yKoMRwV6UQ=w1200-h630-p" width="48" align="right"><div>Google Docs</div><div><strong><a href="https://docs.google.com/spreadsheets/d/1RatJDM_f9_3bvYhl3Bpq2d8SyKgtVdrV1RkGxPU17c8/edit?usp=embed_facebook">Scenarios</a></strong></div><div>Basic

Action to be done,Result,Release,Status,Why does not work?
DONE: 24/28 (86%)
Double click Enso executable.
,Unnamed project opens with two connected nodes `0 . up_to 100 . to_vector . map noise` and second `sort` with open scatterplot visualizations. Connections should have colors.,First,N...</div></blockquote>

**Comment by wdanilo** [comment]
@farmaazon I have never experienced it TBH. When I was collapsing nodes, then after entering nodes and entering the newly created function, it was looking OK. If I have ever seen something like that I would definitely raise an alarm. Seriously, I have never seen it - look at all our tutorials on youtube where we are collapsing nodes - after entering the function they look 100% correct (they place is as it was earlier, not random)
