### ISSUE TITLE
Unclear message about unsupported engine version

### ISSUE THREAD

**Issue by wdanilo** [enso-org/ide#1235]
After opening the newly installed IDE I see an error about the unsupported engine version, but the error does not mention to me where the `package.yaml` file is, so as a user I would be lost:

![image](https://user-images.githubusercontent.com/1623053/108986642-a629eb80-7692-11eb-8db0-982d4637a26d.png)

It should also mention that you can remove `~/enso` instead, which would remove your projects, and then restart the GUI.

**Comment by sylwiabr** [comment]
Should't we change the default size of a window to be able to fit the message here?![Screenshot 2021-02-25 at 12.33.36.png](https://images.zenhubusercontent.com/5953b61961b4ca3b0a72960b/f40f9c6e-447d-413c-a2b0-2f7a4410542a)
