### ISSUE TITLE
Some visualizations not working

### ISSUE THREAD

**Issue by wdanilo** [enso-org/ide#1238]
In the newest release candidate I can see the following behavior:

![image](https://user-images.githubusercontent.com/1623053/108988209-7c71c400-7694-11eb-8d64-34e108d8962c.png)

**Comment by sylwiabr** [comment]
<img width="477" alt="Screenshot 2021-02-24 at 12 53 39" src="https://user-images.githubusercontent.com/12892578/108996933-530a6580-769f-11eb-920f-1f09faf4404e.png">
can not reproduce

**Comment by farmaazon** [comment]
Also can't reproduce.
