### ISSUE TITLE
Histogram visualization is not working correctly

### ISSUE THREAD

**Issue by wdanilo** [enso-org/ide#1243]
Histogram visualization is showing incorrect results:

![image](https://user-images.githubusercontent.com/1623053/108990059-a6c48100-7696-11eb-920d-042d8c2c1739.png)

**Comment by farmaazon** [comment]
I see the result is correct? In every bucket we have two values, except 0-1 where we have one.

**Comment by sylwiabr** [comment]
<img width="310" alt="Screenshot 2021-02-24 at 13 05 01" src="https://user-images.githubusercontent.com/12892578/108998247-eb551a00-76a0-11eb-984c-1048472dcd61.png">
this is 0 to 19

**Comment by sylwiabr** [comment]
Enhancement to be added: We should not set default intervals but have single bar with single value BUT we should give a user an option to set intervals

**Comment by MichaelMauderer** [comment]
> Enhancement to be added: We should not set default intervals but have single bar with single value BUT we should give a user an option to set intervals

Figuring out how to do this will probably part of the visualization API discussion. Right now setting buckets requires a specific JSON configuration to be sent with the data.

**Comment by farmaazon** [comment]
Improving visualization moved to another issue enso-org/ide#1486
