### ISSUE TITLE
Panning/zooming in visualizations is inconsistent with rest of IDE

### ISSUE THREAD

**Issue by wdanilo** [enso-org/ide#1245]
All our gestures, like zoom and pan should be consistent across the whole GUI. They are not. 2-fingers drag gesture pans the graph and zooms visualizations (scatter plot, and histogram, maybe others). It works correctly for table and JSON.

**Comment by MichaelMauderer** [comment]
Part of this issue is now in https://github.com/enso-org/ide/issues/1284

**Comment by MichaelMauderer** [comment]
Another part of this issue is now https://github.com/enso-org/ide/issues/1285
