### ISSUE TITLE
Broken internal state of visualizations

### ISSUE THREAD

**Issue by wdanilo** [enso-org/ide#1246]
1. I had this scene:
    ![image](https://user-images.githubusercontent.com/1623053/108991531-872e5800-7698-11eb-8bf8-78fc233032e5.png)
2. Then I removed the node in the middle and I have this scene. I can even **hide and show visualizations and I still get the results there**!
    ![image](https://user-images.githubusercontent.com/1623053/108991583-93b2b080-7698-11eb-82d3-4934b624af3e.png)

**Comment by farmaazon** [comment]
I cannot reproduce this. When I remove the middle node, I receive this:
![image](https://user-images.githubusercontent.com/3919101/109012177-00867480-76b2-11eb-9acf-a29e1e30c941.png)
Is it reproducible on your side?

**Comment by sylwiabr** [comment]
https://user-images.githubusercontent.com/12892578/109020890-accc5900-76ba-11eb-9023-41b729decf71.mov

**Comment by sylwiabr** [comment]
![Screenshot 2021-02-26 at 13.57.10.png](https://images.zenhubusercontent.com/5953b61961b4ca3b0a72960b/00e077a0-35e5-45fc-b22b-33e71903e137) do I need to wait for fix from Engine? I can still reproduce it.
