### ISSUE TITLE
Colors of edges do not update correctly

### ISSUE THREAD

**Issue by wdanilo** [enso-org/ide#1249]
1. Make this graph:
![image](https://user-images.githubusercontent.com/1623053/108993685-33713e00-769b-11eb-9680-9a487280585e.png)

2. Disconnect edge and drop it
![image](https://user-images.githubusercontent.com/1623053/108993719-3d933c80-769b-11eb-8517-4808c0998406.png)

3. Reconnect it back. Here is an error - the connection has the wrong color!
![image](https://user-images.githubusercontent.com/1623053/108993830-5f8cbf00-769b-11eb-9626-f7c0f7557991.png)

4. Open visualization and move the node with the wrong color and the color will update:
![image](https://user-images.githubusercontent.com/1623053/108993936-77fcd980-769b-11eb-84fa-9bb57a024bf7.png)

**Comment by BinarySoftware** [comment]
@farmaazon said that this is probably part of this issue:
![Zrzut_ekranu_1](https://user-images.githubusercontent.com/26655166/111766827-421bd100-88a6-11eb-91cc-3c39e301c015.png)
![Zrzut_ekranu_2](https://user-images.githubusercontent.com/26655166/111766832-447e2b00-88a6-11eb-984a-83c48753328a.png)
![Zrzut_ekranu_3](https://user-images.githubusercontent.com/26655166/111766835-4516c180-88a6-11eb-8c19-8f179ff1baf3.png)

As You can see, some nodes have their type annotations, and some, even though their connection is properly colorured - dont.

**Comment by sylwiabr** [comment]
It should be closed with https://github.com/enso-org/ide/issues/711
