### ISSUE TITLE
The startup takes a long time. There should be indicator that stdlib is compiling.

### ISSUE THREAD

**Issue by wdanilo** [enso-org/ide#1253]
When starting the GUI, we need to wait 30 seconds till everything is ready. A big chunk of this time is spent on first stdlib recomilation. We should show on status bar after startup "Compiling standard library, please wait." until parser is fixed.

**Comment by MichaelMauderer** [comment]
Probably should be added here: https://github.com/enso-org/ide/issues/1105

**Comment by farmaazon** [comment]
This is for the initial nodes coloring? If yes, then I don't know how to do that easily, because AFAIK we don't receive from the Engine any message telling "now the suggestion database is ready". I can remove the indicator upon receiving the first expression update.
