### ISSUE TITLE
It is possible to zoom visualization in such a way that we don't see all the points, but we are unable to pan it

### ISSUE THREAD

**Issue by MichaelMauderer** [enso-org/ide#1285]
### What did you do?
![image](https://user-images.githubusercontent.com/1428930/109630091-cd763200-7b44-11eb-92d7-1fc5ad78d9cd.png)

**Comment by MichaelMauderer** [comment]
@wdanilo Can you clarify what you have observed there and fill in the issue?

**Comment by farmaazon** [comment]
I zoomed and I'm still able to pan. Is it a macOs issue?

**Comment by MichaelMauderer** [comment]
> I zoomed and I'm still able to pan. Is it a macOs issue?

Maybe. This was reported by @wdanilo and should be clarified.

**Comment by wdanilo** [comment]
@MichaelMauderer wait, this was reported by you, as far as I see :D I dont remember what it is about. The only thing that I have in mind here is a bug we discovered with Radek - you can zoom the graph in such way that the visualizaiton occupies 100% of screen estate, then select visualization and you are stuck - you cannot deselecti t with escape, you cannot pan the view out to click the background, and you are just stuck

**Comment by farmaazon** [comment]
I think @MichaelMauderer created this issue on your behalf. And the image does not fit the description. So the issue you spotted with Radek was another one. Has it been reported?

Closing this for now.

**Comment by wdanilo** [comment]
The problem with this issue is that I dont understand the meaning of its title. @MichaelMauderer do you remember anything more here?

**Comment by MichaelMauderer** [comment]
@wdanilo No unfortunately not. This was part of a bunch of things you asked me to file issues about, so I don't have any further details. If I remember correctly the title is what you said and the screenshot is what you sent with it.
