### ISSUE TITLE
Show visualization on output port hover.

### ISSUE THREAD

**Issue by farmaazon** [enso-org/ide#1302]
### Summary
Error visualization should be hidden by default. Hovering output port shows the visualization above the graph (in the front layer), it has to have background an shadows. Error visualization is displayed the same way.

**Comment by farmaazon** [comment]
* The error should be displayed in red/yellow, so the tooltip FRP api should be extended accordingly.

To discuss: which approach is better:
* The tooltip has only text area. Instead of using Error visualization, the visualization message should be just put there. This require some additional layer of setting visualizations to receive Dataflow data and convert them to error messages (this is currently done in Error vis)
* The pop-up can contain the visualization. Error visualization is moved there.

**Comment by farmaazon** [comment]
BR conclusion:
* Error visualization should be hidden by default. Hovering output port shows the visualization above the graph (in the front layer), it has to have background an shadows. Error visualization is displayed the same way.

**Comment by MichaelMauderer** [comment]
@wdanilo Actually what we decided on does not really work well with the existing tooltips. 
Still WIP, but to illustrate the problem: 

https://user-images.githubusercontent.com/1428930/111493078-863f9200-873d-11eb-8c14-f0e48c8b8856.mp4

Either we need to rework the layout, or for now, we refocus the issue on the error text. We could not show the visualization if there is no error, and show no tooltip if there is an error and show the error text only. So avoiding the collision in both cases.

If we rework the layout we could try to move the visualization further down if we show it through the hover action to avoid collision with the type preview tooltip that way. Or we show the preview visualization above the node.

**Comment by wdanilo** [comment]
@MichaelMauderer ouch, you're right. My first thought is that we should:
1. Stick the tooltip below node
2. Move the visualization below tooltp
(so you'll have from top to bottom : node, tooltip, visualization).

But let me think about it till tomorrow and lets chat after standup, ok ?
