### ISSUE TITLE
Theme API for Visualizations

### ISSUE THREAD

**Issue by radeusgd** [enso-org/ide#1337]
### General Summary

Provide the following functions for JS types extending `Visualization`:
- `this.theme.getColorForType` which gets a qualified type name and returns the color that is used in the GUI for that type,
- `this.theme.getForegroundColorForType` which gets a qualified type name and returns the color that should be used for foreground (e.g. text) that is shown on top of the background color returned by `getColorForType`.
- `this.theme.get` a generic function that takes a string name and returns the color, for example `this.theme.get("node")` should return color of nodes or something like that (@wdanilo may probably have more details on this one).

### Motivation

Some visualizations may want to color things according to their types and it will be great if these colors will match the type->color mapping from other parts of the IDE.

**Comment by radeusgd** [comment]
> What colour should `getForegroundColorForType` return? I don't think we have a similar definition so far.

I think @wdanilo may have a more precise answer here, but what I understand is that while the `getColorForType` is the primary color that is used for coloring edges between nodes representing flow of data of that type, it is also used as background for the names:
![image](https://user-images.githubusercontent.com/1436948/111993707-38e56b00-8b17-11eb-9e08-9d2d34802856.png)
so like here, the blue color is the `getColorForType` - it is used for the connections *and* for background of the text `sum1` which has that type. Its counterpart `getForegroundColorForType` is the color of text that is drawn on top of that background (here `sum1`).

**Comment by s9ferech** [comment]
@wdanilo, is there already a definition for this color in the codebase?

**Comment by wdanilo** [comment]
@s9ferech yes, it is defined somewhere in our theme. I cant find it now, talk with Adam and Michael. In case you'll not find it fast, please ping me on Discord and Ill do it after my calls today! But this will be just querying something for theme manager.
