### ISSUE TITLE
The visualizations sometimes get pixelated

### ISSUE THREAD

**Issue by radeusgd** [enso-org/ide#1344]
Some visualizations show as pixelated.

I cannot exactly tell what are the conditions for this.

I managed to get a node for which opening the JSON visualization always showed pixelated text, but for another similar node the text was crisp and I couldn't find any particular differences between these. Moving around, zooming in and out does not seem to affect this.

The most efficient way to reproduce this seems to be to use the following visualization code: [db.js](https://github.com/enso-org/ide/files/6160007/db.txt) (you need the latest engine build that already has the new visualization helpers for Sql to run this). But the actual important part does not rely on that: what should be enough is to create the divs as in the attached example: a container containing a tooltip and a scrollable div filled with text, and move the tooltip div after mouse enters some element on that scrollable div. This scenario triggered pixellated view most of the time for me.

Some pictures for context:
![image](https://user-images.githubusercontent.com/1436948/111543587-8eb2bf80-8773-11eb-9c47-1a0a01ea41f7.png)
![image](https://user-images.githubusercontent.com/1436948/111543613-9a9e8180-8773-11eb-870a-8e531f693be3.png)

### Enso Version

```
Frontend:
    Version:  1.0.0
    Build:    f8576ba7
    Electron: 11.1.1
    Chrome:   87.0.4280.88
```

**Comment by MichaelMauderer** [comment]
Maybe related to https://github.com/enso-org/ide/issues/821

**Comment by radeusgd** [comment]
The blurring also seems to happen when an animation related to the visualization is in progress (an animated CSS property change using the `transition` property).

For example, create a visualization containing a div with following styles:
```
        .tooltip {
            opacity: 0;
            transition: opacity 2s;
            width: 120px;
            background-color: black;
            color: #fff;
            text-align: center;
            border-radius: 6px;
            padding: 5px 0;
            position: absolute;
            z-index: 1;
            bottom: 100%;
            left: 50%;
            margin-left: -60px;
        }
```

and some other element whose `mouseenter` event sets that first div's `opacity` to `1`.

During the (2s) time of the animation, the fonts are blurry for me (running on Linux).

**Comment by farmaazon** [comment]
> Maybe related to enso-org/enso#2502

No, that issue is about fonts displayed in WebGL. For visualization there is an issue enso-org/ide#1432 . Closing as duplicate.
