### ISSUE TITLE
Build fails on clean repo

### ISSUE THREAD

**Issue by MichaelMauderer** [enso-org/ide#1380]

**Comment by farmaazon** [comment]
The build fails only when the first command is `./run watch`. The `./run dist` command works properly.

**Comment by farmaazon** [comment]
And after `./run dist` the subsequent `watch`es work.

**Comment by MichaelMauderer** [comment]
@wdanilo @farmaazon This still works for me. A clean checkout followed by `./run watch` builds and allows me to open the IDE in a working state.
Could you both send a full log of the output that you are seeing for this not working on your end?

**Comment by farmaazon** [comment]
@MichaelMauderer 

I cannot reproduce it anymore.
