### ISSUE TITLE
Visual improvements

### ISSUE THREAD

**Issue by farmaazon** [enso-org/ide#1397]
### Summary
There is a couple of small visual issues:
* [x] Add a gap between searcher list and the searcher input, configurable by themes.
* [x] Searcher list, searcher documentation, and visualization container should have the same shadow as nodes; all shadow parameters should be also taken from themes.
* [x] Searcher suggestion list: padding left is different than padding top (probably due to missing icon - the left padding is a sum of original left padding + gap between icon and text).
* [x] Hide the unused action icons on nodes (skip and freeze).
* [ ] Documentation in searcher: get the background color from the visualizations theme api. *
* [ ] Color of the text in status bar should be obtained from theme manager.
* [ ] There is a little area between node and icons, where icons are hidden on hover. The area should be removed.
* [ ] Searcher list entry: there should be a gap between entries' "hover area" (the area which hovered make the entry selected). The gap should be configurable in themes and set to 4 pixels there. * + explain @wdanilo 
* [ ] The font in searcher documentation and in other places differ in size. *
* [ ] When searching in searcher, the letters matching pattern should be blue, not white. *

**Comment by MichaelMauderer** [comment]
>     * [ ]  Documentation in searcher: get the background color from the visualizations theme api.

This already seems to be the case here: https://github.com/enso-org/ide/blob/9b60a911b959401d9fbe605a113ad0f140fef04b/src/rust/ide/view/src/documentation.rs#L97
Am I missing something?

**Comment by MichaelMauderer** [comment]
>  Searcher list entry: there should be a gap between entries' "hover area" (the area which hovered make the entry selected). The gap should be configurable in themes and set to 4 pixels there.

This needs information because I don't quite understand the issue here. What is supposed to happen if the cursor goes into this area? If we keep the previous selection, how is it different from the current behaviour? Is this meant to also increase the distance between items or is this shrinking the hover area?

**Comment by MichaelMauderer** [comment]
>  Searcher suggestion list: padding left is different than padding top (probably due to missing icon - the left padding is a sum of original left padding + gap between icon and text).

I also just realized I don't understand this one. A screenshot would be helpful. 
On a positive note: I also aligned the searcher suggestion list and documentation.
