### ISSUE TITLE
Adding nodes may result in wrong imports

### ISSUE THREAD

**Issue by BinarySoftware** [enso-org/ide#1441]
### What did you do?
Added Http.new

### What did you expect to see?
import Standard.Base.Network.Http

### What did you see instead?
import Base.Network.Http

### Enso Version
Latest

**Comment by farmaazon** [comment]
The old imports happens when the suggestion database on disk is outdated. As a workaround, remove the `.enso/suggestion.db` file from your project's directory.

**Comment by farmaazon** [comment]
Closing, as the old engine's versions should not be supported anymore. However we should check that when doing the next release.
