### ISSUE TITLE
Add an option for passing options to backend.

### ISSUE THREAD

**Issue by farmaazon** [enso-org/ide#1525]
### Summary
There should be a CLI option which allows to set some set of options to the backend.

### Specification
The example usages should look like:
`--backend-opts --opt`
`--backend-opts "--opt1 foo --opt2"`

**Comment by mwu-tow** [comment]
As per discussions:
* backend options shall be placed after `--` separator
* `--verbose` will be added to IDE and will imply `-vv` backend option
* in future flags and options should be harmonized.
