### ISSUE TITLE
Histogram has wrong bar width for `0.up_to 8 . to_vector`

### ISSUE THREAD

**Issue by MichaelMauderer** [enso-org/ide#1530]
### What did you do?
* Create a vector with `0.up_to 8 . to_vector`
* Open histogram 

### What did you expect to see?
A histogram with bars that are wide enough to touch.

### What did you see instead?
A bar chart with very narrow bars. 

![image](https://user-images.githubusercontent.com/1428930/116073223-68e0da80-a690-11eb-9292-9289b70c7cf7.png)

### Enso Version
8a6d90e

**Comment by farmaazon** [comment]
Well, this is somewhat boud to the "number of buckets" problem. The bar are narrow, because they represent a range like `0.0 - 0.25` I'm not sure how it should behave? Should we shrink the number of bars if the number of values is less than default number of bars?

**Comment by MichaelMauderer** [comment]
Ah you are right. In that case, this is not a bug. Just checked and matplotlib does the same.
