### ISSUE TITLE
Disconnect should revert port name

### ISSUE THREAD

**Issue by MichaelMauderer** [enso-org/ide#1552]
### Summary
When we  remove a connection on a port we lose the port name, and it is replaced with an underscore. Instead, we should restore the name of the port (if there is one). 

https://user-images.githubusercontent.com/1428930/117297519-9ee34300-ae76-11eb-92ff-19f1b8bbd17b.mp4

### Value
Nodes will be  easier to read while working on them. 

### Specification
If a port has a name, and an edge is disconnected from the port, the port name should be restored. If no name is available, the underscore can still be used as a placeholder. 

### Acceptance Criteria & Test Cases
Test scenario showing that this is working as intended.
If possible, an automated test that checks that the content of a node is as expected after an edge has been removed in a specific test scenario.

**Comment by iamrecursion** [comment]
> If no name is available, the underscore cans till be used as a placeholder.

Under what circumstances would a port not have a name? Every function argument in Enso is named, so surely every port should also be named?

**Comment by MichaelMauderer** [comment]
Just thinking of potential corner cases:

1. in the video, would the port `number` have a default name when we remove the connection to the source? 
2. do we have argument names for operands, e.g., if we have a node created as `var1 + var2` and remove one of the connections? 
3. there might also be the case where the node has an error and refers to a non-existing function, so any bets about port names are off.

**Comment by iamrecursion** [comment]
Good point on the 2nd one, but once [shadow definitions](https://github.com/enso-org/enso/issues/1239) are done there won't be any _valid_ function that doesn't have names.

**Comment by wdanilo** [comment]
@MichaelMauderer:

1. This is covered here: https://app.zenhub.com/workspaces/enso-ide-5e99c2847b8a3027b334f1b9/issues/enso-org/ide/1554
2. Do we have a situation now where args are not named? How can it happen @iamrecursion? In order to define operators, we are providing names, right?
3. Good point, I described the desired behavior here: https://app.zenhub.com/workspaces/enso-ide-5e99c2847b8a3027b334f1b9/issues/enso-org/ide/1551

**Comment by iamrecursion** [comment]
> Do we have a situation now where args are not named? How can it happen @iamrecursion? In order to define operators, we are providing names, right?

Unfortunately so. We have builtin definitions that don't really get connected through. The shadow definition work will close that gap.

**Comment by sylwiabr** [comment]
this should be fixed with https://github.com/enso-org/ide/issues/711
