### ISSUE TITLE
Cursor is not visible in the cloud

### ISSUE THREAD

**Issue by stasyaner** [enso-org/ide#1573]
### What did you do?

1. Get vpn credentials from @lolczak.
2. Clone [cloud-ui repo](https://github.com/enso-org/cloud-ui/tree/wip/st%2Fproj-settings-form).
3. Update `ENSO_IDE_VER` variable at line 20 of `pages/ide/[projectId].tsx` file to "2.0.0-alpha.6.rc.4" (the latest rc version from enso-org/ide-staging).
4. Update the project name propert at the line 101 of the same file to the actual name of the project you are going to run (for e.g. "New_Project_1").
5. Run it using the instructions from the readme.
6. Create a project and start it.
7. Open the project.

### What did you expect to see?

Cursor should be visible.

### What did you see instead?

Cursor is not visible.

### Enso Version

alpha-6.rc.4

### Additional notes
Cursor is actually there but it's 1 screen height lower. See the screencast below.

![alpha-6 rc 4-cursor-issue](https://user-images.githubusercontent.com/9165512/118508488-88b76b80-b72f-11eb-9453-bf1095128b49.gif)

**Comment by MichaelMauderer** [comment]
Could you add details about your screen resolution and display setup?

**Comment by farmaazon** [comment]
I found the root problem: we do the transformation of cursor's y position, so our 0.0 point is at left-bottom corner and y grows upwards. To do that, we read the height of `body` element, however, in cloud for some reason the body element has height of 0 (despite containing the properly sized canvas inside).

The question is: should we fix it in IDE (read screen's height from root element, or from canvas) or in cloud (ensure that body element has proper height)?

**Comment by MichaelMauderer** [comment]
Pinging @wdanilo. I remember having a chat about how the IDE should work. Essentially, there is one element that is the root of the IDE, and the size of the IDE should be based on that. I don't think it was the body or the canvas but the div with id `root`.

**Comment by farmaazon** [comment]
Yes, I also thought about taking the size from the `root` element.

**Comment by stasyaner** [comment]
`root` element has absolute positioning, so `body` doesn't have size.
```css
#root {
    height   : 100vh;
    width    : 100vw;
    margin   : 0;
    position : absolute;
    overflow : hidden;
}
```
