### ISSUE TITLE
Many shortcuts not working on Windows 10 2104

### ISSUE THREAD

**Issue by kragil** [enso-org/ide#1631]
On my Windows install I wanted to see the the code view so I tried pressing ctrl + `  ( keypress keyCode=96  (`)   which=96  (`)   charCode=96  (`) , but also tried all others like ' ´  ) and nothing happened. I also tried both alt and Windows keys and shift.

German Windows and German keyboard.

**Comment by iamrecursion** [comment]
I can reproduce this on macOS (en_GB) using an alternative (PC-style) keyboard layout.

**Comment by iamrecursion** [comment]
This is probably the same issue as enso-org/enso#2901.

**Comment by MichaelMauderer** [comment]
> This is probably the same issue as enso-org/enso#2901.

It is. So, I'm closing this as duplicate.
