### ISSUE TITLE
Incorrect node movements

### ISSUE THREAD

**Issue by stasyaner** [enso-org/ide#1650]
### What did you do?

- Load IDE
- Create a `0` node
- Move it

### What did you expect to see?

Node moves normally.

### What did you see instead?

Node moves with some offset.

### Enso Version

alpha.6

### Additional notes
![ide_strange_behavior_30jun21_1117](https://user-images.githubusercontent.com/9165512/123935952-ff818e80-d994-11eb-86a6-58df5c71c44c.gif)

**Comment by mwu-tow** [comment]
This is side effect of https://github.com/enso-org/ide/issues/1626
