### ISSUE TITLE
Scatter plot area selection offset

### ISSUE THREAD

**Issue by farmaazon** [enso-org/ide#1800]
### What did you do?
In fresh project, I zommed and panned the view a little, and then show the scatter plot visualization and tried to do the area selection inside.

### What did you expect to see?
A selected area according to the mouse click and move.

### What did you see instead?
The area appears with offset, which depends somehow on the pan/zoom state (however I haven't checked exactly how).

### Enso Version
alpha.12 draft release

**Comment by mwu-tow** [comment]
I believe this is covered by https://github.com/enso-org/ide/issues/1429

**Comment by farmaazon** [comment]
Closing in favor of enso-org/enso#2873
