### ISSUE TITLE
Cursor should blink only when it's idle

### ISSUE THREAD

**Issue by notdanilo** [enso-org/ide#282]
### General Summary
Cursor should stop blinking when we interact with text editor so we can keep track of its position.

### Steps to Reproduce
Focus text editor and hold space.

### Expected Result
Cursor should only blink when it's idle.
It should be visible when we are typing or navigating

### Actual Result
Cursor keeps blinking. If we hold space, we lose track of it.

### Enso Version
core : 2.0.0-alpha.0
build : 6d3fe64
electron : 8.1.1
chrome : 80.0.3987.141

**Comment by farmaazon** [comment]
I would say, it's not 1.

**Comment by farmaazon** [comment]
Seems like already covered by Text Editor Part 1, @wdanilo can you confirm that?

**Comment by wdanilo** [comment]
It's already done. Closing
