### ISSUE TITLE
[BUG] Installer goes red and doesn't do anything

### ISSUE THREAD

**Issue by NightMachinary** [enso-org/ide#447]
![image](https://user-images.githubusercontent.com/36224762/82608833-a27faa80-9bd0-11ea-976e-0f9276ddf297.png)
This is a freshly downloaded installer. After clicking install it becomes like this and is totally useless.

**Comment by wdanilo** [comment]
@NightMachinary thanks for reporting. Could you try the command line installer from our website? Unfortunatelly, we will not fix this issue, as we have a new installer in Luna 2.0 and it should be released in a month or two :)
