### ISSUE TITLE
Ability to change text on nodes via GUI

### ISSUE THREAD

**Issue by wdanilo** [enso-org/ide#462]
### Summary
There should be an easy way to edit expression on nodes. The UX design is tricky here. It needs to be easily accessible but also should not prevent other more important UX patterns, like entering the nodes. Basically, in ideal visual representation, nodes should be designed so well and should allow for such a fluent workflow, that manual editing the expression should be used very rarely - in most cases user should just connect edges, collapse nodes, go inside, etc. Thus, double-clicking a node should be used to go inside the node (and double-clicking the background should allow traverse to the parent scope). Node expressions should be editable either by `cmd / ctrl + LMB` shortcut (which collides now with multi-select, but we can leave `shift + LMB` as multi-select, as used in a lot of apps, incl. Houdini, MaxMSP, or LabView)

### Specification
- `cmd / ctrl + LMB` to edit a node expression.
- `enter` / `background click` to accept the new expression.
- `escape` to cancel editing and get back to previous expression (this was added as a new point after the implementation and may be refactored to separate issue).

### Acceptance Criteria & Test Cases
- Integration with IDE

**Comment by sylwiabr** [comment]
Let's think here about names on the nodes and possibility to edit them by user via GUI

**Comment by sylwiabr** [comment]
adding there a slider mode (issue https://app.zenhub.com/workspaces/enso-ide-5e99c2847b8a3027b334f1b9/issues/enso-org/ide/103)

<blockquote><img src="No image" width="48" align="right"><div><img src="/dist/favicon/favicon-16x16.png" height="14"> ZenHub</div><div><strong><a href="https://zenhub.com">ZenHub</a></strong></div><div>Project Management and Software Development with GitHub | ZenHub</div></blockquote>

**Comment by sylwiabr** [comment]
I can not accept a task without any description. Please fill the description and acceptance criteria. @wdanilo @farmaazon

**Comment by sylwiabr** [comment]
1. `Enter` does not accept text on node - it creates new line
2. It should be possible to edit text on the node if you click anywhere - right now if you have node `Foo.bar baz` you have to click on `Foo`

**Comment by farmaazon** [comment]
> 1. `Enter` does not accept text on node - it creates new line

@sylwiabr That was fixed in PR with searcher view.

> 2. It should be possible to edit text on the node if you click anywhere - right now if you have node `Foo.bar baz` you have to click on `Foo`

Still to be done.

**Comment by wdanilo** [comment]
2. I'd love to fix it as part of https://github.com/enso-org/ide/issues/528 , as this will be strongly connected. If you agree, please check this again.

**Comment by sylwiabr** [comment]
I will then accept it with enso-org/ide#528 @wdanilo . Until then it should remain open.

**Comment by sylwiabr** [comment]
@farmaazon @wdanilo ad 1 is not working if the input is string i.e. "foo bar baz" then `enter` adds new line
