### ISSUE TITLE
 Expose ability to switch themes (dark / light).

### ISSUE THREAD

**Issue by wdanilo** [enso-org/ide#463]

**Comment by MichaelMauderer** [comment]
This task is missing a description. 
Is this meant as an internal API? Available through shortcut? Or should there be a full visual settings menu?

**Comment by farmaazon** [comment]
We'll add proper description when planning next release. Let's focus on tasks  for Community Alpha Release (Closed), especially the bug reports.

**Comment by BinarySoftware** [comment]
Huh, actually with light mode the shortcut has been added, so IF this is the ability (and it works, currently only changes background, but should also be able to change all the items with some tweaks) then the task is done ...

**Comment by farmaazon** [comment]
As the shortcut does not change themes properly (changing background only is _not_ proper theme switch), the task definitely is _not_ done.

**Comment by farmaazon** [comment]
Closing in favor of https://github.com/enso-org/ide/issues/795
