### ISSUE TITLE
Moving IDE window on MacOS and Windows is not possible

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/ide#484]
### General Summary

Moving IDE window on MacOS is impossible.
### Steps to Reproduce

Open IDE and try to change its position.
### Expected Result

IDE has changed its position 
### Actual Result

[Screen Recording 2020-05-26 at 09.37.57.zip](https://github.com/luna/ide/files/4681003/Screen.Recording.2020-05-26.at.09.37.57.zip)

### Enso Version

core     : 2.0.0-alpha.0
build    : 10f0760
electron : 8.1.1
chrome   : 80.0.3987.141

**Comment by BinarySoftware** [comment]
Actually it is possible, but very unintuitive - when you hover over the top edge the resizing cursor shows up, but then do not resize the window, but hold it and drag it left or right - now you can move the window. I think that there should be approx. 10px translucent border to drag the window right under the edge

**Comment by sylwiabr** [comment]
Interesting. I was able just to resize it, not drag.

**Comment by wdanilo** [comment]
Cannot reproduce on my side. Research needed on each platform separately.
