### ISSUE TITLE
IDE fails to start if the Main.enso file is deleted

### ISSUE THREAD

**Issue by mwu-tow** [enso-org/ide#510]
### Steps to Reproduce
Run IDE once.
Delete file `enso\projects\Project\src\Main.enso`
Rerun IDE.

### Expected Result
IDE should start and gracefully handle issue.
In short term it likely should just recreate the file with default content.

### Actual Result
IDE fails to load, console error is:
```
(unknown) panicked at 'Failed to setup initial project view.: RemoteError(Error { code: 1003, message: "File not found", data: None })', src/libcore/result.rs:1165:5
```

### Enso Version
60cedc4d28610f6355753f8d9e6c6c567edcb731

**Comment by farmaazon** [comment]
We agreed for the simplest solution: to recreate Main.enso with some hard-coded content.

**Comment by mwu-tow** [comment]
We also should consider if project manager shouldn't provide some help here, as a project without `Main.enso` is not valid.

**Comment by kustosz** [comment]
Both solutions sound terrible. Of course it is valid to have a project without main, what if it's a library? So why would you auto-add it?

**Comment by wdanilo** [comment]
@kustosz hmm, shouldnt libraries contain `Main.enso` as well? Connected question, let's imagine you create a library "Kustosz". What will happen if I write `import Kustosz : Marcin` ? Where the struct `Marcin` will be defined in the library? I mean, should the `Main.enso` not be the "root" interface of library potentially re-exporting the most useful things?

**Comment by kustosz** [comment]
> @kustosz hmm, shouldnt libraries contain Main.enso as well?

They should? Maybe, dunno. I don't feel comfortable _enforcing_ it though, if the author doesn't need it :)

>  I mean, should the Main.enso not be the "root" interface of library potentially re-exporting the most useful things?

I love the idea, could you please open a design-discussion issue in our repo so that other people can voice their opinions in the proper place?

**Comment by wdanilo** [comment]
Sure, I will. But then, I will force every library and every binary to have `Main.enso` file as an entry file.

**Comment by kustosz** [comment]
OK, but then I'll remove that file every time language server starts.

**Comment by mwu-tow** [comment]
The design discussion should move to https://github.com/enso-org/enso/issues/1050

This issue shall be only about implementing a provisional workaround that allows IDE to start by recreating a missing `Main.enso` file.
