### ISSUE TITLE
Incorrect port display on operator expressions

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/ide#517]
### General Summary

If user put a code:
```
main = 
    foo = 7
    bar = foo + 10
    baz = 12
```
he will not be able to change a connection from `foo` to `baz` inside `bar`, just connect `baz` instead of `10`
### Steps to Reproduce

[Screen Recording 2020-06-02 at 16.15.46.zip](https://github.com/luna/ide/files/4717741/Screen.Recording.2020-06-02.at.16.15.46.zip)

### Expected Result

updated note to `bar = baz + 10`
### Actual Result

`bar = foo + baz`
### Enso Version

core : 2.0.0-alpha.0
build : 60cedc4
electron : 8.1.1
chrome : 80.0.3987.141

**Comment by wdanilo** [comment]
Confirmed with @sylwiabr, it is not working on operators but works on normal function shapes. Seems like a bug in port visualization.

**Comment by wdanilo** [comment]
![image](https://user-images.githubusercontent.com/1623053/87753154-3bfabf80-c802-11ea-8ef6-ab03a28810bd.png)

In this example, `foo` is handled as a node name, thus you cannot connect things to it
