### ISSUE TITLE
Example, useful visualization set.

### ISSUE THREAD

**Issue by wdanilo** [enso-org/ide#534]
- Table visualization (taken from old Luna implementation) (4 days)
- Map (google maps or mapbox) (4 days)
- Histogram (1 day)
- Linear plot (1 day)

**Comment by MichaelMauderer** [comment]
For this task, do just want to have a bunch of very basic example visualizations, or are we going to start implementing a whole "visualization backend". For that I mean: proper handling of axes (labels, categories vs continuous data), scaling/panning/zooming of the visualization, animations for state changes etc. This task could go arbitrary deep, so I think we need to be clear about (a) where the limits are but also (b) where we are going with this in the future, to keep in mind how we want to extend this.

**Comment by sylwiabr** [comment]
1. This will be Java Script based
2. It is a starting point  but should be a good example for the regular users to build their own visualizations 
3. @wdanilo let's talk about the limits and update this issue after

**Comment by MichaelMauderer** [comment]
Then I assume we will be using an existing visualisation library to  build the examples? Something like d3?
