### ISSUE TITLE
Provide information about argument names to the node editor

### ISSUE THREAD

**Issue by mwu-tow** [enso-org/ide#535]
### Summary
The span-tree on node's inputs should contain information about argument name if it's available:
* when we received "methodCall" field in ExpressionValueUpdate.
* when there is stored "intended method" information in node's metadata, and it's up to date.

### Specification
* The input of span-tree generator should take the information about function call (probably just the suggestion database entry). Then, if the AST is a prefix chain, each node representing function call argument should contain the argument name in an extra field of `span_tree::Node`.
* Whenever we receive the update from Engine regarding new methodCall for some node, the graph editor view should be notified about new span-tree on such node (to properly refresh the labels on ports).

### Acceptance Criteria & Test Cases
The updated view, or logs in console if view will be not ready yet.

**Comment by iamrecursion** [comment]
The implementation of the engine's support for the searcher will provude the necessary information for this functionality to the IDE. As part of the searcher support, the IDE will receive (and get updates for) a database of hints. 

This operates as follows:

- The database initially contains all functions available in the project. For each function, it will contain:
  - A primary key.
  - The name.
  - Some identifier.
  - A list of arguments. For each argument this will contain its name, whether it has a default value (and the textual expression for that value), and, where possible, the type of the argument.
  - Where possible, the return type of the function.
- This database will get updated by messages from the engine as the IDE moves its execution context around. These updates will introduce (and remove) locals as needed by the engine.
- When asked for completions at a position in a scope, the engine will respond with a list of identifiers that key into the hints database, and potentially some additional rows for that database on the fly.
- The list of identifiers will be _ranked_ based on relevance, but performing textual filtering to subsequently re-rank these is the IDE's job. 

To this end, the hints database should provide all the information necessary for the IDE to display argument names in the editor.
