### ISSUE TITLE
Add menu to select visualisation for given type + test switching visualizations

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/ide#541]
### General Summary

For a given type can be available many different visualizations. To allow user to select the visualization he wants we need to provide a dropdown menu. The visualizations listed should be taken from the visualizations registry and prioritized - the visualizations defined in current projects should be on top of the list etc.

This needs
- additional UI for selecting the visualization (similar to a text list widget)
- integration with the registry to filter valid visualization for the node output type

### Motivation

Better visualizations usability for users.

**Comment by MichaelMauderer** [comment]
@wdanilo Would it make sense to actually split this into smaller tasks according to the bullet points? 

This could reduce PR complexity if we had first a PR for a "text list widget" in a debug scene, then the dummy node UI system, and then integration of both parts. 

(Or we could just treat them as sub-tasks with separate PRs, with no need for separate tickets)

---

Clarification questions:
Do we have designs for what the icons in the UI should be like? 
I assume the icons should be implemented as custom shapes.

**Comment by wdanilo** [comment]
@MichaelMauderer , as we've been discussing yesterday, this is already split and this description was a little bit too broad (edited already). This task is ONLY about implementing 1 icon and 1 drop-down menu to select visualization type. 

Regarding the visual view, let's do it this way - after you HOVER visualization, on top of it (right upper corner with a few pixel distance from borders), there should appear a dark, transparent, rounded rectangle with the name of the current visualization selected and a triangle down. A VERY FAST sketch:
<img width="288" alt="vis choose" src="https://user-images.githubusercontent.com/1623053/88390464-a8ecf700-cdb8-11ea-8fb6-2e364c215373.png">

This is o course just a rough preview - the rectangle should be dark transparent, the arrow should not have a line, and the spacing should be better + the corner radius should be "matching" the outer corner radius (Should be smaller, but the corner circle should have the same center as the corner circle of the vis background).

After pressing this button, a drop down should appear, and its appearance should be similar to this:
![image](https://user-images.githubusercontent.com/1623053/88390650-f9fceb00-cdb8-11ea-9118-832b597eb661.png)

**Comment by sylwiabr** [comment]
one issue here: https://github.com/enso-org/ide/issues/837
