### ISSUE TITLE
Editable project name in view.

### ISSUE THREAD

**Issue by notdanilo** [enso-org/ide#585]
### Summary
This task is to add control displaying project name, which will be docked to the top-center point of the window (and thus over the node view). 

User can click on this name and start to edit it. When user press enter, the name is commited; text field loses focus and FRP signal about project name change is emitted - the actual project rename will be implemented in #584.

The name should be dark gray and highlighted when mouse hovers over it, or when it is edited.

### Value
This is a user-friendly way to renaming projects, far better than popping-up dialog. 

### Acceptance Criteria & Test Cases
Tests and a working example

**Comment by wdanilo** [comment]
Danilo, based on the video that you have provided, there are several things that look bad right now:
1. There is no indication when the field is active. Part of the task was to make it dark when not in edit mode, light when in edit mode. This is not done.
2. When you are doing renaming (the text is light) and you press escape, you should "cancel the renaming", while hitting "enter" should apply the renaming. After hitting enter, the name should get back to grey state to show the editing is done.
3. After name is changed, the text should not be in editable form anymore, so cursor should not be there.
4. The text needs to be centered, also while typing.

Moreover, on the posted video I have noticed that the text size on nodes and the text size of the project name are different. What is causing it?

**Comment by sylwiabr** [comment]
Completely not working on MacOS but closing in favor of https://github.com/enso-org/ide/issues/693
