### ISSUE TITLE
Text Editor 2.0 (Part 2/2)

### ISSUE THREAD

**Issue by wdanilo** [enso-org/ide#623]
Continuation of  [Text Editor 2.0 (Part 1)](https://github.com/enso-org/ide/issues/591). In particular:
- Displaying selections in the view.
- Connecting all cursor movements to keyboard actions.
- Allowing text edits from keyboard (not only from API like now).
- Allowing placing multiple cursors / multiple selections.
- Implementing text scrolling.
- Fixing some bugs (sometimes after the window loses focus, the text stops being responsive).

Please note that this task will probably not include copy/paste functionality. I need to collaborate with @farmaazon to implement it properly.

**Comment by sylwiabr** [comment]
how can I check it? there is no acceptance criteria.

**Comment by farmaazon** [comment]
There was a debug scene with multiline text editor with some colors, but I don't see it here now.
@wdanilo could you restore it back?
