### ISSUE TITLE
Flatbuffers Code Doesn't Compile Using Stable `flatc`

### ISSUE THREAD

**Issue by iamrecursion** [enso-org/ide#624]
### General Summary
Compiling the IDE using `./run check` with a stable version of `flatc` in the path regenerates the files and causes compilation to fail.

### Steps to Reproduce

1. Install the latest stable version of the `flatc` compiler.
2. Run `./run clean`.
3. Run `./run check`.

### Expected Result
It compiles.

### Actual Result
It fails to compile

### Enso Version
`6b89b6830f9ff29043e17c56f4f3b258749a0b6a`

**Comment by farmaazon** [comment]
I think we should require to specific env variable to be set to regenerate files and add proper instructions to the CONTRIBUTING.md

**Comment by mwu-tow** [comment]
The [bug in flatbuffers compiler](https://github.com/google/flatbuffers/issues/5055) has been fixed after last stable release and they haven't bumped version yet so we cannot even discern good fbs compiler from a buggy one.
So yes, an opt-in mechanism like env var should be added.
