### ISSUE TITLE
Enso Studio crashes while opening on macOS Big Sur

### ISSUE THREAD

**Issue by BinarySoftware** [enso-org/ide#650]
Tested on latest commit from main, macOS Big Sur (11.0) beta 1 & beta 2

### General Summary
Application tries to launch but crashes immediately. Thought that this was electron-related issue, but it seems that it is not. 

### Steps to Reproduce
Build IDE or download from artifact
Open on macOS 11.0

### Expected Result
Application launches

### Actual Result
Application crashes

### Enso Version
latest

**Comment by farmaazon** [comment]
The exact commit where the bug was spotted: 13efe30aef785090894aab1432659c5ee5a27d2e 
Why it seems that it's not an electron issue @BinarySoftware ?

**Comment by BinarySoftware** [comment]
It seems like that, as other electron-based apps seem to work on macOS BS, like VS Code, Messenger or whatsapp launch properly - maybe there's something with electron config which bothers BS, but idk, to test that everything has been compiled properly i took the app compiled on BS and run it on Catalina, without any problems. Idk, maybe it's something with [app notarization](https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution). Here i'll also leave [macOS release notes](https://developer.apple.com/documentation/macos-release-notes/macos-big-sur-11-beta-release-notes) and [appKit rn](https://developer.apple.com/documentation/macos-release-notes/appkit-release-notes-for-macos-11), if that may help

**Comment by BinarySoftware** [comment]
> The exact commit where the bug was spotted: [13efe30](https://github.com/enso-org/ide/commit/13efe30aef785090894aab1432659c5ee5a27d2e)
> Why it seems that it's not an electron issue @BinarySoftware ?

Actually, it was spotted as soon as i got macOS 11 beta up and running, about 2 weeks ago - [21c55da](https://github.com/enso-org/ide/commit/21c55da906bfcb247c91fa03aab79a7a62840661)

**Comment by BinarySoftware** [comment]
If somebody follows this issue here - it is related to yargs, and there's a pr for that

**Comment by wdanilo** [comment]
The pr was rejected. It still needs a proper solution but its good know that we are on a right track!

**Comment by BinarySoftware** [comment]
As a update of situation: Enso Studio opens on BS **without** any mods, but with `./run start`, so there must be something different in the config of `./run dist`. I'll keep investigating.
