### ISSUE TITLE
"Collapse nodes" action in Graph View

### ISSUE THREAD

**Issue by farmaazon** [enso-org/ide#667]
### Summary
The Graph Controller should expose "collapse nodes" functionality available in double_representation module.
Then this method should be integrated with view - the view should have "collapse nodes" action with assigned shortcut.

### Acceptance Criteria & Test Cases
User can collapse selected nodes using the appropriate shortcut.

**Comment by wdanilo** [comment]
After selecting a set of nodes, there should also be icon to collapse them!

**Comment by farmaazon** [comment]
@wdanilo said in different task:
> I've got one request here. I would like to get information about collapsed nodes as different FRP inputs than just "delete" node inputs, as we would like to show animation of collapsing several nodes into a new node. Thus there should be a new FRP input like collapse_nodes : frp::Source<Vec<NodeId>,NodeId> (the second id is the new node created). The handling of this frp should be super simple now - just remove all the nodes, but please keep this FRP so we can add animations whenever we want to

As for icon - we create a separate task for visual part. Here we just add new FRP input and make some simple usage of it.
