### ISSUE TITLE
It is not possible to accept new project name on MacOS in IDE 

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/ide#693]
### General Summary

there are to main problems in editing project name on macOS:

1. it is not possible to accept new project name by pressing `Enter` - it is moving cursor to the project name beginning
2. to start editing project name I can not click on project name - I need to click on the right from the visible name
### Steps to Reproduce

[https://app.zenhub.com/files/213233145/5402f087-111c-4c6f-b35d-23118c5ec51f/download](https://app.zenhub.com/files/213233145/5402f087-111c-4c6f-b35d-23118c5ec51f/download)
### Expected Result

Project name has changed after accepting
### Actual Result

project name is not changed
### Enso Version

core     : 2.0.0-alpha.0
build    : 14990b4
electron : 8.1.1
chrome   : 80.0.3987.141

**Comment by sylwiabr** [comment]
Ok actually I have some renamed projects saved but it is completely not visible from the GUI perspective - the edition is not finished just the cursor is changing the position.

**Comment by notdanilo** [comment]
@sylwiabr as I mentioned in a private chat, the old `Text Field` has some limitations and it cannot be defocused. I created a task (https://github.com/enso-org/ide/issues/696) to create correct visual feedback while refactoring our codebase with the `Text Field 2.0` and I will link it to this issue.

**Comment by farmaazon** [comment]
@notdanilo actually the "defocus" operation is very simple to implement, you have to just set None to `focused_on` field in `FocusManager` which is accessible inside TextField. So making "Defocus" function should be trivial.

**Comment by sylwiabr** [comment]
actually in package
core     : 2.0.0-alpha.0
build    : 6daa8c0
electron : 8.1.1
chrome   : 80.0.3987.141
it is not possible to edit the project name

**Comment by sylwiabr** [comment]
actually works on newest main, my mistake
