### ISSUE TITLE
CI build randomly fails

### ISSUE THREAD

**Issue by MichaelMauderer** [enso-org/ide#704]
### Summary
CI sometimes fails to build / check / lint while a local build or even a rebuild works fine.

### Value
Being able to reliably run CI without delays for searching for potential build issues or waiting for rebuilds.

### Specification
Something causes CI to sometimes fail. We need to research why this is the case and fix it.

### Acceptance Criteria & Test Cases
Report on the likely cause of the issue and a fix for it.

Since this is a finicky issue, we might find a re-occurrence for different reasons, so we should keep a proper record of what we thought was the cause and hoe we fixed it, so if it occurs again, we can come back to this issue and expand the research.

**Comment by MichaelMauderer** [comment]
Note: from my observations, it seemed like builds tended not to fail if the cache for the cargo registry was skipped.

**Comment by mwu-tow** [comment]
I believe that @BinarySoftware also observed that disabling cache helps this random failures.
TBH I think that to properly solve this we eventually should:
1) split checks and packaging and have only the former block PRs
2) move blocking parts where possible to self-hosted machines

Even with cache it is still slow and apparently the mechanism is fragile as well. As a compiled language Rust is just really have when compared to CI machines capabilities.

**Comment by MichaelMauderer** [comment]
A note after looking at the configuration: could the problem be the shared cache between `Build`/`Linter`/`Tests`? Maybe they need separate caches if the builds between them differ somehow?

**Comment by farmaazon** [comment]
As I wrote in PR https://github.com/enso-org/ide/pull/708 I start to doubt if this cache helps us really at all. The most time-consuming job is not improved at all (with and without cache takes 42 minutes), however I checked 2 commits only. Perhaps we could do more investigation.

**Comment by MichaelMauderer** [comment]
I'll keep this open as a reminder to investigate and re-instate caching. Unless we want a new issue for that.
