### ISSUE TITLE
Prepare Dark Mode style for Documentation View

### ISSUE THREAD

**Issue by BinarySoftware** [enso-org/ide#709]
### Summary
As the documentation view is now viewable in Enso Studio, it should be viewed correspondingly to the main App Theme, Either dark or light.

### Value
Docs look good

### Specification
Creates Stylesheet file and corresponding methods for Documentation View

### Acceptance Criteria & Test Cases
Docs look good

**Comment by sylwiabr** [comment]
How can I check it? `cmd+alt+shift+t ` shortcut is not working @BinarySoftware

**Comment by farmaazon** [comment]
@sylwiabr Closing for now. Let's accept it once the switching will be implemented.
