### ISSUE TITLE
Remove TODOS from documentation, and give proper information.

### ISSUE THREAD

**Issue by farmaazon** [enso-org/ide#739]
### Summary
1. In _Getting Started_ section there are invalid links. It also points to the releases list, but there are no releases yet.
2. There is no information how to obtain packages from actions - it should be put in contributing guide at least.

**Comment by farmaazon** [comment]
Blocked until the exact way of running things will be cleared out.

**Comment by sylwiabr** [comment]
![image](https://user-images.githubusercontent.com/12892578/103271999-00bd0900-49bc-11eb-8519-1faa331a7af9.png)
The documentation how use our package and how use IDE with separately downloaded PM should be updated. Currently there is an information in `help` that you can pass a path to local PM but how can user manage it? what about downloaded engine, not only PM?
