### ISSUE TITLE
Incorrect Exit Behaviour on macOS

### ISSUE THREAD

**Issue by iamrecursion** [enso-org/ide#742]
### General Summary
The application doesn't display proper macOS-native exiting behaviour.

- All macOS applications respond to the `⌘ + Q` shortcut by exiting.
- The application does not exit when all windows are closed. This is not a _truly_ consistent behaviour due to some older apps, but all modern macOS applications (including the default ones) exit when there are no open windows remaining (this can be seen with Notes, Photos, Messages, etc.)

### Steps to Reproduce
Part 1:

1. Open Enso Studio
2. Press `⌘ + Q`

Part 2:

1. Open Enso Studio.
2. Close the window using the red `x`.

### Expected Result
Part 1: The application should quit.

Part 2: The application should quit.

### Actual Result
Part 1: The application doesn't quit.

Part 2: The application remains open.

### Enso Version
```
5a4ba838f86d121ba6dd2980829a9bca32e3d56a
```

**Comment by sylwiabr** [comment]
`cmd+q` works for me on version
core     : 2.0.0-alpha.0
build    : 3042282
electron : 8.1.1
chrome   : 80.0.3987.141

for closing with `x` there will be another issue opened

**Comment by wdanilo** [comment]
I don't understand what does it mean that `x` should close app. It should hide it only, this is how apps on MacOS work. The current behavior is correct. Regarding cmd+q, this PR should fix it: https://github.com/enso-org/ide/pull/1088
