### ISSUE TITLE
Editing Keys Don't Work Properly in the Node Editor

### ISSUE THREAD

**Issue by iamrecursion** [enso-org/ide#749]
### General Summary
A whole host of editing keys don't work in the node editor.

### Steps to Reproduce

1. Open Enso Studio.
2. Cmd + Click to start editing text on a node.
3. Press `Del`.

### Expected Result
A forward delete happens.

### Actual Result
Nothing happens.

### Enso Version
```
5a4ba838f86d121ba6dd2980829a9bca32e3d56a
```

**Comment by farmaazon** [comment]
Name says about many keys, but only one is put into description.

Please add the other one to the list at https://github.com/enso-org/ide/issues/309

**Comment by iamrecursion** [comment]
What do you mean by the other one?

**Comment by farmaazon** [comment]
> A whole host of editing keys don't work in the node editor.

This suggest that this is more than just Delete?

**Comment by iamrecursion** [comment]
Ah, sorry. I couldn't get `Backspace`, the arrow keys, or `Home/End` working.

**Comment by farmaazon** [comment]
Ok, so even the arrow keys - so it seems to be much more than in an issue I linked.

**Comment by iamrecursion** [comment]
Yeah!

**Comment by sylwiabr** [comment]
can not reproduce on:
core     : 2.0.0-alpha.0
build    : 3042282
electron : 8.1.1
chrome   : 80.0.3987.141
