### ISSUE TITLE
Holding Modifiers While Typing Duplicates Keys

### ISSUE THREAD

**Issue by iamrecursion** [enso-org/ide#750]
### General Summary
Holding a modifier key while typing results in that key-press being executed twice.

### Steps to Reproduce

1. Open Enso Studio.
2. Select the text field.
3. Press `Ctrl + D`.

### Expected Result
It is interpreted as a shortcut.

### Actual Result
It results in `dd` being typed.

### Enso Version
```
5a4ba838f86d121ba6dd2980829a9bca32e3d56a
```

**Comment by farmaazon** [comment]
Should be fixed by https://github.com/enso-org/ide/issues/713

**Comment by sylwiabr** [comment]
can not reproduce on
core     : 2.0.0-alpha.0
build    : 3042282
electron : 8.1.1
chrome   : 80.0.3987.141
