### ISSUE TITLE
Cannot Deselect Nodes

### ISSUE THREAD

**Issue by iamrecursion** [enso-org/ide#751]
### General Summary
Sometimes nodes aren't deselected when clicking on the background.

### Steps to Reproduce
Please note that this is an inconsistent reproduction. It doesn't happen 100% of the time.

1. Open Enso Studio.
2. Select the node.
3. Click on the background.

### Expected Result
The nodes are deselected.

### Actual Result
The nodes remain highlighted.

### Enso Version
```
5a4ba838f86d121ba6dd2980829a9bca32e3d56a
```

**Comment by mwu-tow** [comment]
Selecting nodes also seems utterly broken and fails for me randomly.

**Comment by sylwiabr** [comment]
can not reproduce on
core     : 2.0.0-alpha.0
build    : 3042282
electron : 8.1.1
chrome   : 80.0.3987.141
