### ISSUE TITLE
Numerical errors in Animations

### ISSUE THREAD

**Issue by farmaazon** [enso-org/ide#757]
### General Summary
Sometimes numerical errors in animations makes animation infinite. This can be hit e.g. when listView displays 13000 entries and scrolled to bottom.

### Steps to Reproduce
Launch example animation.rs

### Expected Result
The logs eventually ceases to be printet

### Actual Result
Logs are printed infinitely.

### Enso Version
5a4ba838f86d121ba6dd2980829a9bca32e3d56a

**Comment by s9ferech** [comment]
This seems to be solved by PR enso-org/ide#1776. @farmaazon Can you confirm this?

**Comment by farmaazon** [comment]
It seems to be. Check the animation.rs example as described in this issue: is the logs stop being printed, then it is fixed.
