### ISSUE TITLE
Maximizing IDE on macOS freezes IDE until you change the active window, for example by invoking mission control

### ISSUE THREAD

**Issue by BinarySoftware** [enso-org/ide#771]
### Steps to Reproduce
Open IDE
Click green maximize button

**Comment by farmaazon** [comment]
@BinarySoftware Do you still reproduce this bug?

**Comment by BinarySoftware** [comment]
No, no longer :) But our custom mouse makes the mouse invisible when hovering over mac's window control, IDK what about linux or windows, could someone check this behavior?

**Comment by wdanilo** [comment]
@BinarySoftware good to hear its not longer valid. It wokrs on my side as well. Please report the second bug (invisible mouse) as separate issue with a giff showing it please.

**Comment by BinarySoftware** [comment]
> @BinarySoftware good to hear its not longer valid. It wokrs on my side as well. Please report the second bug (invisible mouse) as separate issue with a giff showing it please.

Ok :D https://github.com/enso-org/ide/issues/859
