### ISSUE TITLE
Electron: Cannot open developer tools on Windows

### ISSUE THREAD

**Issue by BinarySoftware** [enso-org/ide#785]
### General Summary
clicking Ctrl+Shift+I should show dev tools, which show up on other platforms, like on mac with option+cmd+I

### Steps to Reproduce
click Ctrl+Shift+I 

### Expected Result
Dev tools panel show up

### Actual Result
It does not.

**Comment by farmaazon** [comment]
I'm not so convinced that we want to implement this shortcut. The fact we use electron an we have web application inside is an internal thing. The errors should be some day displayed to user in the main view. Additionally to see logs you can just pass `--dev` option when launching application (at least on Linux it works).

**Comment by sylwiabr** [comment]
Yes, the behaviour we want to keep right now is - if you want to have dev tools run the app with `--dev` flag
