### ISSUE TITLE
Looping through visualizations does not work.

### ISSUE THREAD

**Issue by BinarySoftware** [enso-org/ide#786]
### General Summary
Looping through visualizations require hiding and showing it or moving node to present visualization with data from node.
This is __NOT__ an issue with tab view btw.

### Steps to Reproduce
open enso studio, create node, for example a string containing valid json presentable in tab view and loop to tab view

### Expected Result
tab view shows.

### Actual Result
you need to hide and show vis and then tab view shows.

**Comment by MichaelMauderer** [comment]
@BinarySoftware Could you add the commits from the engine and Enso version that you used to observe this issue?

**Comment by BinarySoftware** [comment]
@MichaelMauderer It still happens btw - so latest commits : https://github.com/enso-org/ide/commit/09b2db6ce8de4c0e4ceec83d661abb18a1163dd6
https://github.com/enso-org/enso/commit/c0de753d9572711706b1edf73168a190aa6e0cf8
