### ISSUE TITLE
Crash reporting

### ISSUE THREAD

**Issue by farmaazon** [enso-org/ide#808]
### Summary
Our application should graciously handle all panics which may appear in rust code, and send the reports to the appointed server.

### Value
Bugs in our code can be easily reported by users and fixed by us.

### Specification
Our application is essentially a web application packed with electron, and all logic is implemented in Rust, and compiled to the WASM. The js part only loads the WASM module and call one entry_point function.

* Create a simple service gathering the crash reports and writting them to the file with date.
* Whenever rust code panics, the whole page displayed in electron should be refreshed. After refresh the information about crash should be displayed in a html element being a red box at the top of the page. The user should have options to send the report or dismiss the message.
* If application crashes again while information about previous crash is still displayed, the refresh should be skipped, and all html elements except the crash message removed.
* The report should contain the string representation of PanicInfo, and the stacktrace.
*  Address and port of the service should be obtained from application options, and default to localhost and arbitrary picked port. The connection error with service should not be fatal.
* The panic message should also be printed to the console (like it is currently), for convenience of debugging.

### Acceptance Criteria & Test Cases
Test with service run on localhost and application with modified rust code:
* with `panic!` during initialization (some function of `IdeInitializer`)
* with `panic!` during some user interaction, e.g. moving node (`GraphEditorIntegratedWithControllerModel::node_moved_in_ui`).

**Comment by s9ferech** [comment]
I would like to work on this.

**Comment by s9ferech** [comment]
In case of a panic, I think it would be best to reload the whole content of the application window from inside through `location.reload()`. But for security reasons, we currently prevent this inside the Electron window:
https://github.com/enso-org/ide/blob/3d0ea7d6c77e46996dcede07138a9b9da97453a9/src/js/lib/client/src/index.js#L240-L251

An alternative solution would be to do the reload from the Electron main process. But this would not work when you open the GUI in another browser.

Another solution would be to try and reset the original state of the window by hand. But there is a high risk that this would not be done correctly.

@farmaazon, do you have a suggestion how I should handle it?

**Comment by wdanilo** [comment]
@s9ferech I was implementing the Electron part, so let me answer your questions here. You have correctly found out that:

1. `location.reload` is banned for pretty common security reasons (it is advised to be disabled by official electron docs).
2. Window restart is rather a bad idea, as it would involve a ton of system-specific corner cases, some special window management process, etc - we definitely don't want such a heavyweight solution here. 
3. Reloading the website from electron main process is bad as well – we want this to work in our cloud app as well.

Taking into consideration all the above points, I would advise yet another solution, which is by the way mentioned in the docs that you have pasted within your question: https://www.electronjs.org/docs/tutorial/security#12-disable-or-limit-navigation , namely;

> If your app has no need for navigation, you can call event.preventDefault() in a will-navigate handler. If you know which pages your app might navigate to, check the URL in the event handler and only let navigation occur if it matches the URLs you're expecting.

We know exactly what addresses we want to allow from within electron - this is the address our server runs on (the server address and port are set up within main electron process, so you can grab them pretty easily there). Do you see any downsides of this solution? If not, this is super simple to be implemented and should work fine and securely.

**Comment by s9ferech** [comment]
Thanks, this is clearly the right solution.
