### ISSUE TITLE
Cannot show visualizations or select multiple nodes.

### ISSUE THREAD

**Issue by BinarySoftware** [enso-org/ide#824]
### General Summary
Regression introduced on latest master.
Furthermore, cannot select multiple nodes.

### Steps to Reproduce
open project, select node, click cmd+space

### Expected Result
visualizations pops up

### Actual Result
native macOS spotlight search pops up and not visualization in IDE

**Comment by sylwiabr** [comment]
works for newest main (https://github.com/enso-org/ide/pull/832)
