### ISSUE TITLE
Nodes selection shortcuts does not work

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/ide#826]
### General Summary

It is just possible to select a node and after select another one. All the selection shortcuts does not work.
### Steps to Reproduce

Open IDE 
add 3 nodes
try to use all Node Selection shortcuts described here: https://dev.enso.org/docs/ide/product/shortcuts.html
### Expected Result

Shortcuts work as described
### Actual Result

nothing happens
### Enso Version

core     : 2.0.0-alpha.0
build    : 9e1ad61
electron : 8.1.1
chrome   : 80.0.3987.141

**Comment by sylwiabr** [comment]
in version:
core     : 2.0.0-alpha.0
build    : 08849e8
electron : 8.1.1
chrome   : 80.0.3987.141

- single node selection works
- multiselect with shift works
- deselection with option command works

**Comment by farmaazon** [comment]
After recent fixes most of those shortcuts work. The "drag area" selection doesn't, however it never did and it is covered in enso-org/enso#2293.
The other one not working properly is inverse selection in case when I press shift first, then alt. When I click alt first, then shift, it works. Tested on linux.
