### ISSUE TITLE
Missing visualizations for some types i.e. list of Integers

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/ide#836]
### General Summary

Most of the nodes should have visualizations available - at least the text visualization. For some of them - like list of integers - additional visualizations should be visible. In this case it should be table visualization and scatterplot.
### Steps to Reproduce

Open IDE
add node `[1,23,45,67,89,234]` or `10.sin`
show the visualziation
### Expected Result

3 possible and working visualizations:
- text
- table
- scatterplot
### Actual Result

![Zrzut ekranu z 2020-10-06 13-56-47.png](https://images.zenhubusercontent.com/5953b61961b4ca3b0a72960b/7ba1d84e-d21f-476a-a27f-4846fc38eb7e)
### Enso Version

core     : 2.0.0-alpha.0
build    : 08849e8
electron : 8.1.1
chrome   : 80.0.3987.141

**Comment by mwu-tow** [comment]
The underlying issue is the Language Server reporting node value to be `null`, reported as https://github.com/enso-org/enso/issues/1232

**Comment by sylwiabr** [comment]
Right now I am getting visualization for `1.0` but I don't for list of integers![Zrzut ekranu 2020-10-30 o 08.44.27.png](https://images.zenhubusercontent.com/5953b61961b4ca3b0a72960b/0efb325c-10df-45c9-944c-200ed467297b)![Zrzut ekranu 2020-10-30 o 08.45.41.png](https://images.zenhubusercontent.com/5953b61961b4ca3b0a72960b/266369cb-9710-4db6-a307-5577d8718620)

Enso Project Manager
Version:    0.1.0
Built with: scala-2.13.3 for GraalVM 20.2.0
Built from: main* @ 36694e249655d2bba183867b1bdef7519242ac0d
Running on: OpenJDK 64-Bit Server VM, GraalVM Community, JDK 11.0.8+10-jvmci-20.2-b03
            Mac OS X 10.15.7 (x86_64)
IDE:
core     : 2.0.0-alpha.0
build    : 17e4190
electron : 8.1.1
chrome   : 80.0.3987.141

**Comment by sylwiabr** [comment]
Actually visualizations works if I will manually add `to_json` method ![Zrzut ekranu 2020-10-30 o 10.56.14.png](https://images.zenhubusercontent.com/5953b61961b4ca3b0a72960b/459e7eef-7c9c-4be0-b25a-9a76e05a6d65)

**Comment by farmaazon** [comment]
Investigated a little, but the IDE requests seems ok, so I wrote comment on the engine's issue
