### ISSUE TITLE
Show button not working in documentation panel

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/ide#840]
### General Summary

<img width="312" alt="Zrzut ekranu 2020-10-8 o 13 42 10" src="https://user-images.githubusercontent.com/12892578/95454065-37aaf200-096c-11eb-8f34-44e00374fec3.png">

### Steps to Reproduce

Open Searcher in IDE
go through hints with available docs
try to see the example 
### Expected Result

The example is shown after clicking on `Show` button
### Actual Result

Nothing happen
### Enso Version

core     : 2.0.0-alpha.0
build    : 08849e8
electron : 8.1.1
chrome   : 80.0.3987.141

**Comment by BinarySoftware** [comment]
I'll fix it on the engine side.

**Comment by farmaazon** [comment]
Ou, I'd rather say that issue is not-passing event to js. And it could be fixed also on IDE side.

**Comment by sylwiabr** [comment]
acceptance blocked by https://app.zenhub.com/workspaces/enso-ide-5e99c2847b8a3027b334f1b9/issues/enso-org/ide/852

<blockquote><img src="No image" width="48" align="right"><div><img src="/dist/favicon/favicon-16x16.png" height="14"> ZenHub</div><div><strong><a href="https://zenhub.com">ZenHub</a></strong></div><div>Project Management and Software Development with GitHub | ZenHub</div></blockquote>

**Comment by BinarySoftware** [comment]
There's no "show" button in IDE anymore, hence I don't think this issue is relevant
