### ISSUE TITLE
When in full screen on macOS and using our custom mouse, user wont see system mouse on the buttons

### ISSUE THREAD

**Issue by BinarySoftware** [enso-org/ide#859]
This is probably next of many electron-related issues

screen grab:

![2020-10-20 19 03 37](https://user-images.githubusercontent.com/26655166/96619984-1ac8d400-1307-11eb-9f61-64f51c33efe2.gif)

**Comment by sylwiabr** [comment]
does not occur on 
core     : 2.0.0-alpha.0
build    : 65acecb
electron : 8.1.1
chrome   : 80.0.3987.141
