### ISSUE TITLE
Visualizations doesn't show in visualization panel on MacOS

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/ide#865]
### General Summary

Visualizations doesn't show in visualization panel on MacOS
### Steps to Reproduce

open IDE
add node `23`
open visualization by clicking `space` or eye icon
### Expected Result

visualization below the node
### Actual Result

![Zrzut ekranu 2020-10-22 o 11.21.32.png](https://images.zenhubusercontent.com/5953b61961b4ca3b0a72960b/b39da269-05da-4022-b526-e7ee16ee2ffb)
### Enso Version

core     : 2.0.0-alpha.0
build    : 51e09ff
electron : 8.1.1
chrome   : 80.0.3987.141

**Comment by BinarySoftware** [comment]
I've checked that and here's my research:
Clicking on Eye icon simply shows/hides vis panel container, but doesn't truly invoke vis show. Pressing space bar on node works as expected - i've been able to show/hide vis properly with it. Latest Engine and IDE commit (https://github.com/enso-org/ide/commit/51e09ff96b03dce812e39f2b2971557f433a2cd0)

**Comment by BinarySoftware** [comment]
As i've expected: Here are logs from :
Space show/hide:
```
[IdeInitializer.Project Controller.ExecutionContext bd4c2095-0e21-4e4d-95e9-03afdb683d1f] Inserting to the registry: 7c1a44f6-3171-4a05-adb6-e3cb752b20cb.
VM60:1570 [IdeInitializer.ws://127.0.0.1:64867] Sending text message of length 353
VM60:1566 [IdeInitializer.binary-protocol-client] Processing incoming transport event
VM60:1570 [IdeInitializer.Project Controller.ExecutionContext bd4c2095-0e21-4e4d-95e9-03afdb683d1f] About to detach visualization by id: 7c1a44f6-3171-4a05-adb6-e3cb752b20cb.
VM60:1570 [IdeInitializer.ws://127.0.0.1:64867] Sending text message of length 246
VM60:1570 [IdeInitializer.Project Controller.ExecutionContext bd4c2095-0e21-4e4d-95e9-03afdb683d1f] Removing from the registry: 7c1a44f6-3171-4a05-adb6-e3cb752b20cb.
```

Eye show/hide:
```
(12 times repeated) Hiding
```

**Comment by farmaazon** [comment]
@BinarySoftware your comments are probably for another issue: https://github.com/enso-org/ide/issues/864 this describes not-showing visualization at all, both when brought by pressing space and by clicking icon.

**Comment by BinarySoftware** [comment]
Yes, that was def a missclick @farmaazon :) but still, i was able to show vis on macOS, so this can be related somehow?

**Comment by sylwiabr** [comment]
fixed already
