### ISSUE TITLE
If there are two vis panels overlapping user can see content of the visualization below

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/ide#867]
### General Summary

If there are two vis panels overlapping user can see content of the visualization below
### Steps to Reproduce

open ide
add two nodes close to each other
show visualizations
### Expected Result

the top visualization cover the bottom one![Zrzut ekranu 2020-10-22 o 11.47.16.png]
### Actual Result

![Zrzut ekranu 2020-10-22 o 11.47.16.png](https://images.zenhubusercontent.com/5953b61961b4ca3b0a72960b/320c09dd-1d60-4c40-b77d-b1c31b34bd09)
### Enso Version

core     : 2.0.0-alpha.0
build    : 51e09ff
electron : 8.1.1
chrome   : 80.0.3987.141

**Comment by farmaazon** [comment]
Apparently the `RawText` visualization should create a background in its diff.

**Comment by sylwiabr** [comment]
there is one more thing to be fixed: the visualization on the active node should be on the top
![image](https://user-images.githubusercontent.com/12892578/98544539-73e7b000-2294-11eb-8578-ade204d0b3e1.png)

**Comment by MichaelMauderer** [comment]
@sylwiabr I will have a look but this might be considerably more difficult until we get the proper solution (#913).

**Comment by sylwiabr** [comment]
O so I will create comment there!
