### ISSUE TITLE
Add "copy" button to examples in documentation.

### ISSUE THREAD

**Issue by farmaazon** [enso-org/ide#902]
### Summary
Because it is hard to get the Ctrl+C shortcut working in current IDE state, there should be an utility button for copying examples in documentation.

### Value
Able to show examples in docs actually working.

### Specification
The button should be created in html generated by docs parser.

### Acceptance Criteria & Test Cases
Working in IDE.

**Comment by sylwiabr** [comment]
![Screenshot 2021-01-11 at 17.17.57.png](https://images.zenhubusercontent.com/5953b61961b4ca3b0a72960b/aea60747-1aa5-4626-b704-009eaaf8c43c) there is no copy button on MacOS ![Screenshot 2021-01-11 at 17.18.51.png](https://images.zenhubusercontent.com/5953b61961b4ca3b0a72960b/63d0bb6d-e25d-4537-a7ec-3352ee6fae6d)
