### ISSUE TITLE
Implement a z-order mechanism for shapes.

### ISSUE THREAD

**Issue by MichaelMauderer** [enso-org/ide#913]
### Summary
This is a tracking/reference issue for a bigger architectural issue of the EnsoGL issue: z-ordering of shapes.

At the moment there is no mechanism to determine the order of shapes instances, and different base shapes are ordered by order of their first instantiation.  This leads to many occlusion issues, and we need a way to define (a) order between different shapes (b) order between different shape instances.

### Value
Allows us to resolve occlusion issues between UI elements, which resolves glitches when object occupy the same space.

### Specification
We need a new design for the EnsoGL rendering pipeline that can accommodate objects with different z-depth (or an equivalent mechanism). 

### Acceptance Criteria & Test Cases
* A design that can be implemented 
* New tasks for new version of EnsoGL
* New tasks for the refactoring of the current UI to work with it the new version of EnsoGL

**Comment by sylwiabr** [comment]
Thing to remember during implementation:
![image](https://user-images.githubusercontent.com/12892578/98549401-04c18a00-229b-11eb-85ac-31d275afbfb4.png)
visualization/documentation/searcher for the active node should be on the top

**Comment by farmaazon** [comment]
@wdanilo How much you're newest PR https://github.com/enso-org/ide/pull/1090 covers the problems described here? I know that we can define the ordering between different shape systems (kinds), but not sure about shapes in the same system?

Please add a bullet list with things-done and things-we-still-can-do in the task description.

**Comment by wdanilo** [comment]
@farmaazon we are able now to define z-ordering of:
1. Scene layers, where each layer can have a registered sprite / shape system. Also, if you add a shape using display object hierarchy to another layer, another shape system will be automatically created there to manage that shape. So this is the first mechanism.
2. We can define the ordering of shapes / sprites within a single layer.
3. We are not able to define the ordering between shapes / sprites withn a single sprite system / shape system. I'm not sure it will ever be needed TBH. If it will be needed, we can add it, it should be pretty simple task (but CPU-time consuming). Ordering shapes within sprite / shape system would require the whole buffer for that sprite system to be reuploaded (approx (10 x sprite count) floats) on every ordering. I dont see a reason why we would need it. In fact, if you need it, it sohuld probably be expressible with the mechanisms (1) and (2), which are CPU-free.

**Comment by farmaazon** [comment]
Then I will close it for now. If we will need the 3. then we create an issue for it.
