### ISSUE TITLE
Pressing `Esc` in node editor is making the project name dissapear

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/ide#921]
### General Summary

If user is not working with text field (editing project name) but is working with node editor the events should not affect project name
### Steps to Reproduce

Open IDE
focus on node editor
press `esc`
### Expected Result

nothing happened
### Actual Result

project name dissapeard
### Enso Version

core     : 2.0.0-alpha.0
build    : 8a39c8a
electron : 8.1.1
chrome   : 80.0.3987.141

**Comment by sylwiabr** [comment]
That was back in `In Progress` due to the problems we had during testing scenario:
1. The cursor didn't disappear when the project name edition was over and text editor was hidden
2. It was possible to edit breadcrumbs (function name)
3. It happened that project name was edited during nodes edition

Is it working properly now? @MichaelMauderer @farmaazon

**Comment by MichaelMauderer** [comment]
No, I was not aware of that. I thought the issue status was misplaced. 
I will look at that next.

**Comment by MichaelMauderer** [comment]
@sylwiabr It might be good to open new issues with more information for each of those things.
I can't seem to reproduce (1) (2).

(3) is probably also related to enso-org/ide#937 which seems related to focus management. I'm following up on that and can easily also provide a quick fix for this specific scenario.

**Comment by sylwiabr** [comment]
Ok I will create separate issues for 1 and 2 and fill them as soon as I will have full repro.
