### ISSUE TITLE
Text visualization looks bad.

### ISSUE THREAD

**Issue by wdanilo** [enso-org/ide#933]
![image](https://user-images.githubusercontent.com/1623053/98668144-c1752300-234f-11eb-9f84-74598cf6e16d.png)

There is no spacing on the left side, the font looks bad (it should be of the same family as rest of the gui), the font is too small and too gray.

**Comment by sylwiabr** [comment]
The styles should be the same as in the Table visualization

**Comment by BinarySoftware** [comment]
I'll take it 👍 shouldn't be exhausting
