### ISSUE TITLE
Tooltips about types on the ports

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/ide#960]
### General Summary

For users' convenience, the ports should have types labeled (on hover).

**Comment by farmaazon** [comment]
BR:
* Each component should be able to say what the cursor's label is, and in some global context there's a monoid for deciding what label from various components should be taken (the same way as with cursor shape).
* In fact, this can be added to the current `cursor::Style` structure. It should also have an information where label should be displayed (left,right,top,bottom of the cursor).
* The label should have a background.
* The showing and hiding the label should be delayed in the same manner as port are shown/hidden with delay. The delay should be managed by the cursor implementation and it should be attached to showing and hiding the label only. Switching between labels should not have any delay (when the label is already shown). There should be no need to stop mouse to see the label.
