### ISSUE TITLE
Missing edge when creating a function taking another node as input

### ISSUE THREAD

**Issue by MichaelMauderer** [enso-org/ide#961]
### General Summary

![Peek 2020-11-17 17-10](https://user-images.githubusercontent.com/1428930/99415259-e8a39580-28f7-11eb-9d31-3a33e59f2805.gif)

### Steps to Reproduce
1. Create a string node `"a b"`
2. Select node
3. Press tab
4. Select "split at"
5. Press enter

### Expected Result
The new node should be connected to the selected node.

### Actual Result
No connection.

### IDE Version
ec5b0e03597c6e84d91698160dbd75f68cd9caf3

**Comment by wdanilo** [comment]
@farmaazon I'm not getting `connect_nodes` event here. In fact I'm not getting any events in GUI in this scenario, so I suspect something has to be wrong on your side here.
