### ISSUE TITLE
It is possible to edit an argument name

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/ide#969]

**Comment by wdanilo** [comment]
I don't understand this issue. Could you describe it / show examples?

**Comment by sylwiabr** [comment]
I can't reproduce after https://app.zenhub.com/workspaces/enso-ide-5e99c2847b8a3027b334f1b9/issues/enso-org/ide/961 fix

<blockquote><img src="No image" width="48" align="right"><div><img src="/dist/favicon/favicon-16x16.png" height="14"> ZenHub</div><div><strong><a href="https://zenhub.com">ZenHub</a></strong></div><div>Project Management and Software Development with GitHub | ZenHub</div></blockquote>
