### ISSUE TITLE
Edges incorreclty connected when choosing `Vector.map` from searcher with `map` also in the local scope.

### ISSUE THREAD

**Issue by MichaelMauderer** [enso-org/ide#995]
### General Summary
When there is a name class in the local scope, the searcher uses the wrong local function, instead of the expected type specific one.

### Steps to Reproduce
1. Open project 
```
from Base import all

main = 
    map = "UK"
    breakfast = "spam ham eggs spam ham spam spam"
    breakfast.split " "

```
2. Select node `breakfast.split " "`
3. Press tab to create node
4. Type `map`. Now `Vector.map` should be selected.
5. Press enter.

### Expected Result
A new node that uses the `Vector.map` function should be created. This node should be connected to the output of the split `node`.

### Actual Result

![Peek 2020-11-26 09-21](https://user-images.githubusercontent.com/1428930/100325460-f5e01480-2fc8-11eb-9cb0-df38c15db61e.gif)

### System Information
IDE 65acecb3d65f70a62f0abaecdd2049013d9176fa
Engine [e62f6796](https://github.com/enso-org/enso/actions/runs/378897019)

**Comment by farmaazon** [comment]
As I see, the inserted node is correct. operator1 should be a new node name, as we need some name to connect previous node to the new one.

The only glitch I see here are connections.

**Comment by MichaelMauderer** [comment]
You are probably right. Especially regarding the Enso issue about name resolution. When I first saw this, I assumed this was an issue about the wrong `map` being chosen (local versus `Vector.map`).  
The "correct" result would be for the edge to be connected from `"UK"` to `map` and from the split node to `operator1`

**Comment by farmaazon** [comment]
This scenario should not happen anymore, as the UFCS was removed.
