### ISSUE TITLE
Fix output ports coloring and color propagation.

### ISSUE THREAD

**Issue by wdanilo** [enso-org/ide#997]
### Summary
Right now, output ports are not colored and the color propagation is not yet working as it should. This task is about fixin it and closing all color-related issues once and for all.

### Value
Port / edge coloring is one of the most important parts of our user experience. It gives the user important information aobut what they are working with.

### Specification
Ports should be colored accordingly to type information and there should be some kind of central mechanism in graph editor which will unify the coloring information between mouse, edges, input and output ports.

**Comment by sylwiabr** [comment]
One thing worth testing: if I have a type defined inside a project I am always having grey connections while trying to construct it. I.e.
```
type Geo_Point latitude longitude

main = 
    a = 50
    b = 23
    Geo_Point a b
```
