### ISSUE TITLE
Going to the top-level with double-click on the background is starting edition of the project name

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/ide#999]
### General Summary

Going to the top-level with double-click on the background is starting edition of the project name. It does not occur if I am recording a screen but after disabling recording it starts after clicking in the background.
### Steps to Reproduce

add two nodes in IDE, select them and collapse
double-click on newly created node `here.func1` and enter the function
double-click on the background to get to top-level
### Expected Result

nothing special happens, just view changes to toplevel
### Actual Result

after 2-3 s cursor appears on project name textfield and user can accidentally change/delete it
### Enso Version

core     : 2.0.0-alpha.0
build    : 65acecb
electron : 8.1.1
chrome   : 80.0.3987.141

**Comment by MichaelMauderer** [comment]
I can't reproduce the exact behaviour as described on main ( 53b276c3f6620368ee6cb27fdc2587fc43c9616f ) but I see the following behaviour when I leave a node, single click is enough to start editing. No cursor is created on its own though without clicking into the project name field.

**Comment by sylwiabr** [comment]
I will  check if it is system-dependent

**Comment by MichaelMauderer** [comment]
My described behaviour is still a bug, though. And fixing these might be the same problem.

**Comment by farmaazon** [comment]
@MichaelMauderer The PR was reverted due to not working backspace and arrows while editing project name. Please pick your commit and create new PR with fixed version.
